### ISSUE TITLE
updating org and licensing module edit windows

### ISSUE THREAD

**Issue by benheet** [coral-erm/coral#10]
the org and licensing modules use an older style for the edit windows where the layout is more stacked. the later resources module changed to a more broadly spaced layout for the edit windows. this issue is a request to update the org and licensing module edit windows to the layout used by the resources module.

**Comment by jeffnm** [comment]
I'm wondering if this has been addressed in the updated UI from Sirsi?

**Comment by jeffnm** [comment]
I'm going to have one of my programmers tackle this. @bdewar if your UI updates already addressed this, please let us know.

**Comment by jeffnm** [comment]
This never got done.

**Comment by jeffnm** [comment]
Bumping to next release as I won't be able to get it done in time for this one.
