### ISSUE TITLE
Discuss Git workflow

### ISSUE THREAD

**Issue by tuxayo** [coral-erm/coral#104]
@jeffnm https://github.com/Coral-erm/Coral/pull/86#issuecomment-241027870

> [...]some people are downloading the master branch from https://github.com/Coral-erm/Coral which has the session_start() on line 11 while others are downloading the 1.4 release from the old repo (which is recommended) [...]
> 
> [...]this probably needs an issue to be opened, but I would like to suggest that we move to a development model where we only have release merges committed into master and everything else gets pulled into a development branch. That way when someone downloads the master they won't get unstable releases by accident. Something like this: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by tuxayo** [comment]
> some people are downloading the master branch from https://github.com/Coral-erm/Coral

Does this happens because there are 0 releases yet on the unified repo? Meaning that this problem would vanishes at next release?

**Comment by tuxayo** [comment]
> when someone downloads the master they won't get unstable releases by accident

Would having a `release` branch and changing the default branch from `master` to `release` solve the issue?

**Comment by jsavell** [comment]
A development branch is a good idea beyond the issue of installed users. Developers need it, too.

**Comment by tuxayo** [comment]
As a follow up about Git flow and other models such as GitHub flow and GitLab flow, here is a page that discuss about their use cases and is also very informative about general workflow (issues, history, branch life duration, rebase, conflicts) beyond just branch workflow.

http://docs.gitlab.com/ee/workflow/gitlab_flow.html

**Comment by tuxayo** [comment]
>  development branch is a good idea beyond the issue of installed users. Developers need it, too.

I'm assuming that you are answering the proposal of a `release` branch made default:
I didn't mean to delete master, it would still exists and would be the branch were we start working from and integrate our finished work to. Exactly like it's used today.

**Comment by jeffnm** [comment]
> Would having a release branch and changing the default branch (edit: it's a setting on GitHub) from master to release solve the issue?

What's the benefit over having a `Release` branch and a `Master` branch compared to having a `Master` branch(that is nothing but releases) and a `Development` branch? It seems like it's basically the same model. My primary objective is to separate the development work from the release work in a more obvious way and thus keep things clearer and more stable for both end users and developers. 

As long as the default branch on the repository is not also the branch where development work happens, I guess it doesn't matter what we call it. 

> Did it happen before, with the separate repos? That would mean that having 0 releases wasn't the cause.

Yes, it's been an issue. Because pull requests mostly came in fairly finished, it was usually pretty safe to download the master branch. Since releases were so slow to be prepared and published, there was a lot of incentive to do so as well.

**Comment by tuxayo** [comment]
> What's the benefit over having a Release branch and a Master branch compared to having a Master branch(that is nothing but releases) and a Development branch? It seems like it's basically the same model.

This is indeed the same idea, it depends if
- we prefer that the common dev branch stays named `master` (as it's common in many projects) and explicitly have a stable branch named `release`
- or if we keep the stable branch named `master` and have a common `dev`/`developement` branch. which is also common

It's more of which seems more intuitive but it doesn't really matter much.

So shall we go `master`→stable and `dev`→common development branch?

**Comment by tuxayo** [comment]
>> Did it happen before, with the separate repos?

> Yes, it's been an issue. Because pull requests mostly came in fairly finished, it was usually pretty safe to download the master branch. Since releases were so slow to be prepared and published, there was a lot of incentive to do so as well.

Then it will still be an issue, so +1 for two main branches.

**Comment by t4k** [comment]
Commenting here as a new user to CORAL who just came in and cloned `master` initially, it would be helpful to use a development branch, and potentially tags or stub release branches (where the only change is a version number added to files) so we could figure out what the state of the code here is.

**Comment by t4k** [comment]
I think we solved this with our current setup of the **master** branch and **development** branch.

Closing this, but also see #346.
