### ISSUE TITLE
Resource creation: a resource type must be created although using it is not mandatory

### ISSUE THREAD

**Issue by tuxayo** [coral-erm/coral#111]
On a clean Coral install, when trying to create a resource, one gets this message:
![capture d ecran_2016-09-05_12-32-27](https://cloud.githubusercontent.com/assets/2678215/18245329/e9b67ef8-7364-11e6-93b4-93cd938b631f.png)

After creating a resource type in the admin and not even selecting it in the new resource form, it works.

When editing the said resource, one can confirm that it doesn't have a type, so it's not even assigned by default.

Should the resource type be mandatory? Or should the front end let create a resource when no resource type exist?

**Comment by xsong9** [comment]
I don't see the need to have Resource Type as required. Can we just fix the bug that with the clean install, the resource type is required?
