### ISSUE TITLE
Get rid of all DOS line endings

### ISSUE THREAD

**Issue by tuxayo** [Coral-erm/Coral#121]
There is a significant share of the files that have MS-DOS format line endings.

Here are some resources:
https://stackoverflow.com/questions/7068179/convert-line-endlings-for-whole-directory-tree-git/7068241#7068241
https://stackoverflow.com/questions/10629231/convert-all-eol-dos-unix-of-all-files-in-a-directory-and-sub-directories-recu

**Comment by t4k** [comment]
The line endings are all set to LF in PR #207

**Comment by jeffnm** [comment]
I merged #207, but there were some conflicts with some other recently merged pull requests, so it might be good to double check that all line endings are actually LF now.

**Comment by t4k** [comment]
I’ll do this again to make sure we are good.
