### ISSUE TITLE
remove trailing whitespaces

### ISSUE THREAD

**Issue by tuxayo** [Coral-erm/Coral#122]
Part of https://github.com/Coral-erm/Coral/issues/77 section Coding style

Here is an idea of how to proceed.
https://stackoverflow.com/questions/149057/how-to-remove-trailing-whitespace-of-all-files-recursively

**Comment by t4k** [comment]
See pull request #207

**Comment by jcuenod** [comment]
Can this issue be closed?

**Comment by t4k** [comment]
Yes.
