### ISSUE TITLE
"From" Email is incorrect

### ISSUE THREAD

**Issue by veggiematts** [Coral-erm/Coral#123]
In www/resources/admin/classes/common/Email.php, line 38:
`protected $from = "CORAL Resources";`

The From header for sent emails is arbitrary set to "CORAL Resources", which is incorrect.

[RFC 5321](https://tools.ietf.org/html/rfc5321) states that the from should be:

`MAIL FROM:<reverse-path> [SP <mail-parameters> ] <CRLF>`

`<reverse-path>` should be a mailbox at a [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) (mailbox@host.domain)

The first step to fix this should be to set a default value that is correct (no-reply @ result of "hostname -a" for example)

A second step would be for the Coral admin to be able to configure the "From" value (in case the default value is not correct).

Also, reply-to is set to an empty value, and I'm wondering if it's meant that way or if it is an error?

**Comment by veggiematts** [comment]
Do we agree on the solution I propose, in case I make a patch?

**Comment by remocrevo** [comment]
@veggiematts I agree with your idea.  Also, I don't know of any reason not to use the reply-to field.

**Comment by veggiematts** [comment]
See PR #133

**Comment by bdroubay** [comment]
I agree with the patch, and it should be pushed to master as fast as possible. 

Thanks for looking into it.

Brad
