### ISSUE TITLE
Resources bulk import updateDate cannot be null

### ISSUE THREAD

**Issue by t4k** [Coral-erm/Coral#139]
Another timestamp issue. MySQL Engine 5.6.27. Pull request forthcoming.

[Tue Nov 15 23:53:54.793876 2016] [:error] [pid 26331] [client …] PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem with the database: Column 'updateDate' cannot be null' in /var/www/coral/resources/admin/classes/common/DBService.php:39\nStack trace:\n#0 /var/www/coral/resources/admin/classes/common/DBService.php(73): DBService->checkForError()\n#1 /var/www/coral/resources/admin/classes/common/DatabaseObject.php(241): DBService->processQuery('INSERT INTO `Re...')\n#2 /var/www/coral/resources/import.php(498): DatabaseObject->save()\n#3 {main}\n  thrown in /var/www/coral/resources/admin/classes/common/DBService.php on line 39, referer: http://coral/resources/import.php

**Comment by remocrevo** [comment]
Thanks @t4k .
