### ISSUE TITLE
Parent/Child AJAX generates too many DB connections

### ISSUE THREAD

**Issue by remocrevo** [coral-erm/coral#145]
The following report comes from Josh Myles:

No luck with persistent database connections since I believe the code
is explicitly opening and closing connections. I tried prepending the
database server host name with "p:" in all configuration.ini files.

I ended up raising the MySQL connection limit (max_connections=10000)
as well as ulimits for the HTTPd user (nofile nproc both to 10000) and
the large resources loaded.

/resources/resource.php just needs to be refactored. The issue is just
a side effect of the AJAX way in which the page is built. It doesn't
scale for large resources.

The resource we've been testing has 1384 children, which results in
2785 database connections being opened when resource.php is loaded.

**Comment by jeffnm** [comment]
I feel like someone made an attempt to fix this issue previously. I remember someone making changes to the number of mysql connections that were being opened. Perhaps that was a different module that was changed?

**Comment by veggiematts** [comment]
I think the main problem is that a connection is opened for every object instantiated. More than the resources/resource.php page, it's the way we use Objects and database connections that needs to be changed imho.

**Comment by veggiematts** [comment]
I did a small patch that turns the DBService class into a singleton, for the connection to be reused.

If you want to try it to see if it improves performances, it's here: https://github.com/biblibre/Coral/commit/18d017289846d1cf4f756a36cb1805cde64f2585

On my instance, it reduces the processing time for a resource with 3000 children from 5+ seconds to roughly 2 seconds.

**Comment by veggiematts** [comment]
(Moreover, this patch would allow to momentarily change database, allowing us to use objects from other modules, instead of writing SQL statements to gather informations from other modules)

**Comment by jeffnm** [comment]
I'm tagging this issue for 2.1.0 beta milestone. I think we should seriously try to get it in then. I suspect many longterm CORAL users have already changed their `max_connections` setting and so don't notice this as an issue, but the performance boost is enough of a reason to do it.

**Comment by jeffnm** [comment]
Closing as #292 and #343 have both been merged.
