### ISSUE TITLE
Update version number in footer

### ISSUE THREAD

**Issue by remocrevo** [Coral-erm/Coral#146]
Before CORAL 2.0 is released, the footer of every module should say "CORAL version 2.0". I think it shouldn't say the module name like it currently does, since we want people to understand that CORAL is now a single package; modules don't have their own separate versions any more.

This would make the footer identical for all modules, so I propose we add a shared footer.php file that is included by each module.

**Comment by jeffnm** [comment]
I'd like us to include the word Beta for the beta release, but otherwise, I agree completely.

**Comment by jeffnm** [comment]
@remocrevo I see you started this on the remocrevo-2.0-shared-footer branch. Do you mind if I use that same branch to make the changes to include this new common footer for all the other modules?

**Comment by remocrevo** [comment]
@jeffnm That's fine with me.

**Comment by jeffnm** [comment]
Merged #162
