### ISSUE TITLE
Adjust timestamp format for MySQL

### ISSUE THREAD

**Issue by t4k** [Coral-erm/Coral#150]
My previous pull requests had slight errors (#138 and #140). I need to change the format of the timestamps. New pull request forthcoming.

**Comment by jeffnm** [comment]
@t4k Is this still pending? It's tagged with the 2.0.0 Beta milestone.

**Comment by t4k** [comment]
@jeffnm Yes, it is still pending. There is a pull request (#151) that I added to solve the issue. I did not want to merge my own pull request.

**Comment by jeffnm** [comment]
Thanks. I'll go ahead and merge it.
