### ISSUE TITLE
Export notes in Resources module

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/coral#16]
Currently, notes are not part of the export function in Resources. They also don't display in print format. We should add them as they are a very useful source of information.

**Comment by scottvieira** [comment]
Some questions and observations.  Mang and I are thinking that we should export the notes file for each Resources section into a separate csv file providing the Resource ID for linking and possibly the resource title for readability.  So in other words we would export one csv file for product, acquisitions, access and cataloging.  Presently there isn't an export option for the other modules like licensing and organizations so this will have to come later after the Notes functionality is more robust (Issues #33 ) and the modules have been successfully merged.

For the export, each column would represent the custom Note Type value.  This would be repeated if the same Note Type value was used.  The argument for exporting into separate csv files is again the vast ranges of notes possible in each of the Resources section as well as the size of what is contained in the note field.  This would get messy fast if exported in the same file.  However, doing it this way makes it easy for the end users to import all the files into one spreadsheet and link across to different tabs with the Resource ID.  

Comments?

**Comment by techsvcslib** [comment]
I realize that notes can get messy quickly both in terms of number and in extent, but I’d prefer having everything in one spreadsheet. This is much simpler to do and it also facilities use of Excel where columns can be hidden or rearranged as needed.

Steve

**Comment by scottvieira** [comment]
Question should we go to one spreadsheet: How are different libraries using the export function?  And depending upon this use, how important is preserving the relationship between section and placement of note type values in light of many different combinations, including within and outside of the resource record sections using the same Note Type values?  In other words, it seems to me context will be important to the notes.  To make this work we would need to build prefixes to Note Type values exported to show the relationships.    So for examples something like Cataloging_General to describe a General Note type value placed in the Cataloging section of the resource record.  We would also have two additional columns for user and date for each note field.

**Comment by techsvcslib** [comment]
I agree that context is important and it makes sense to me to label them as you propose, Scott. The thing I’m less certain about is the potential impact to the database structure.

Steve

**Comment by fondrenlibrary** [comment]
Steve,

I believe we will not make changes to existing table schema. We just 
need to prefix tab name to  each note field heading  in order to 
maintain context when exporting CSV.

Mang

**Comment by xsong9** [comment]
The issue was resolve.
