### ISSUE TITLE
Coral / ILS interaction: vendors

### ISSUE THREAD

**Issue by veggiematts** [coral-erm/coral#172]
Coral is related to keeping track of electronic resources acquisition. All libraries also have an ILS, that is used for physical materials. 

The goal is to interface Coral with ILSes.

The feature should be:
  - optional (if the user want to keep Coral as a standalone application, nothing must appear on the interface)
  - ILS agnostic (use an abstraction layer to handle the different ILS that want to be linked to Coral)
  - driven by webservices (we assume that both tools can be on different URLs, on different servers. So we will never access the other DB directly)

The first feature would be synchronising vendors:
Vendors must be synchronized between Coral and the ILS. The vendors table of the ILS will be the authoritative one:
  - Any vendor in Coral (ie: an organization with the “vendor” role) will be in the ILS (either created from Coral, or, if it already exist in the ILS, derivated from the ILS)
  - Vendors in the ILS can be or not be in the organizations table of Coral (some vendors are dedicated to non-ER: books, DVD,...)

Feature description:
When an organisation that has a role "ILS vendor" is created in Coral, it must be created also in the ILS. IDs must be shared & stored in both tools.
When an organisation is created in Coral, the librarian can search in the ILS and retrieve the vendor if it exist.

**Comment by jeffnm** [comment]
@veggiematts Can you confirm that #296 resolved this issue (#172)? If so, we can close it too.

**Comment by veggiematts** [comment]
Yes, it does, this issue can be closed.
