### ISSUE TITLE
Installer should not recommend chmod 777

### ISSUE THREAD

**Issue by jamesrf** [Coral-erm/Coral#174]
If the config directory is not writeable, the installer will recommend that you run "chmod 777" on the directories.  This is terrible advice, it should recommend something more conservative.

**Comment by jeffnm** [comment]
You are only prompted to chmod 777 if the installer can't write the configuration files. However, the installer will not complete if those directories are still 777 after the configurations have been written. It prompts you that "It is unsafe to leave your admin directories writable." and asks you to chmod 755 and will not let you proceed until you have changed the permissions back to something other than 777.

**Comment by jamesrf** [comment]
I think that's good, and makes this less urgent.  Although, IMHO it still shouldn't say "chmod 777", it might encourage people to not understand what they're doing.  Other installers such as Drupal and Wordpress don't do that, they just say "Can't write the config file"

PS: Love the installer though, it's great, especially the neat animations!

**Comment by jeffnm** [comment]
Thanks for the feedback! We wanted to have a concrete action that we knew would work for the user, but you are right, it might be encouraging them to do things without understanding why, which is dangerous. We'll have to think some more and see if we can find a better way.

**Comment by jcuenod** [comment]
How about adding a message like this:

```
Note: this command makes files readable, writable and executable by everyone and so is not considered 'safe' but CORAL will remind you to undo this action when the installation is complete.
```

@jamesrf I hear your concern but as Jeff says, this gives users a concrete action to take. In the case of Drupal and Wordpress, if the user gets that error and doesn't know what to do they will almost certainly end up googling and then chmodding like this anyway and quite possibly with no understanding. So I feel like the difference is negligible except that we are not redirecting users to google for troubleshooting. I'm open to alternatives though I just can't think of something better to suggest...

**Comment by jamesrf** [comment]
your reasoning is sound.  I'll close this!
