### ISSUE TITLE
CORAL fails after installation with separate DB host

### ISSUE THREAD

**Issue by jamesrf** [Coral-erm/Coral#175]
I am running the installer with my DB on a separate host (let's call it "dbhost").  I entered this value where it said "Host".  I can get through the installer successfully and get the main menu screen.

When I select a module I get this:
'Access denied for user 'coral_user'@webserver' (using password: YES) in '.... etc

When I peek at the MySQL users table, I see that it has created a user coral_user@dbhost and granted permissions to that.  

I could not find a way to separately specify the db host from the web host.  It might be good to offer that option.  Or, the installer could use '%' as a host, although that may not be ideal as far as principle of least priviledge, so maybe have a note/advice/guide about securing your installation.

**Comment by jeffnm** [comment]
Thanks for reporting this. 

To be clear, 'webserver' is the server that is serving CORAL and 'dbhost' is the server that is running mysql?

**Comment by jcuenod** [comment]
Hi @jamesrf thanks for the feedback!

I just want to clarify your question - you have access denied for `'coral_user'@webserver'` but then you later say "web host" - am I correct in understanding that these are the same thing?

So your Coral install is on `http://coralserver/` but your db is on `mysql://dbserver` (not the more regular `mysql://coralserver`) and the User table should have a grant for `coraluser@dbserver` but instead it has `coraluser@coralserver`?

**Comment by jcuenod** [comment]
Maybe just to follow up, the current grant is happening here: https://github.com/Coral-erm/Coral/blob/master/install/providers/have_default_db_user.php#L119

The line is:

    $db->processQuery("GRANT SELECT, INSERT, UPDATE, DELETE ON {$db_details["dbname"]}.* TO {$db_details["username"]}@{$db_details["host"]} IDENTIFIED BY '$slash_pass'");

So my understanding is that:
Instead of `{$db_details["username"]}@{$db_details["host"]}`
It should be `{$db_details["username"]}@{$_SERVER["SERVER_NAME"]}`

**Comment by jamesrf** [comment]
Apologies for the delay, yes to all the above!

MySQL users are in a format user@host where host is the source of the connection (ie: coral php process running on the server that is running Apache). This allows the MySQL server to identify that the connection is coming from an authorized source

The db connection in php will also have a db host value which is so php knows what host the database is on and can connect to that host.

Hope that clarifies

**Comment by jcuenod** [comment]
Okay, in that case I've just pushed a commit https://github.com/jcuenod/Coral/commit/effe5d098b734b1819d0328773f82cf442010be9 that should fix this issue and it's part of this pull request: https://github.com/Coral-erm/Coral/pull/186

**Comment by jcuenod** [comment]
Just to be clear, I have tested a normal install with this fix but I have not tested a use case like the one you have set up so this needs review.

**Comment by jamesrf** [comment]
Hi!  So I tested but it didn't work -- 
the issue I found is that SERVER_NAME resolved to "localhost" on my machine.  Then the query did the GRANT ALL to user@localhost, which on the db server resolved to itself rather than the webserver. 
I think the solution is to use SERVER_ADDR instead.

**Comment by jcuenod** [comment]
Hmm, SERVER_ADDR is giving me `::1`. Another option is `gethostname()`.
Something I've just discovered though is, without a db selected you can run `SELECT SUBSTRING_INDEX(USER(),'@',-1)` and get the client hostname. Maybe this is the way to go...

**Comment by jamesrf** [comment]
gethostname() did not work for me.  It returns the hostname of that machine, but the database can't resolve the reverse DNS.  It's probably better to use an IP address if possible.  I think my personal preference would be to just have a box (perhaps defaulting to something hidden under "Advanced") that I can put in whatever I want

**Comment by jcuenod** [comment]
what do you mean it can't resolve the reverse dns? surely whatever that string is is what needs to be in the user table?

**Comment by jcuenod** [comment]
The problem with using an ip address is that it's not going to be static. I'm still not understanding what you mean by the db not being able to resolve the reverse DNS but this is the fix I'm proposing:

```php
$db = $shared_module_info["provided"]["get_db_connection"]( $db_details["dbname"] );
$slash_pass = addslashes($db_details["password"]);
try {
	$db_user_result = $db->processQuery("SELECT SUBSTRING_INDEX(USER(),'@',-1)");
	$db_client_host  = $db_user_result->fetchRow()[0];
	$db->processQuery("REVOKE ALL ON {$db_details["dbname"]}.* FROM {$db_details["username"]}@{$db_details["host"]}");
} catch(Exception $e){ }
$db->processQuery("GRANT SELECT, INSERT, UPDATE, DELETE ON {$db_details["dbname"]}.* TO {$db_details["username"]}@{$db_client_host} IDENTIFIED BY '$slash_pass'");
```

**Comment by jamesrf** [comment]
Hey!  Apologies, I meant DNS lookup, not reverse DNS.  If we GRANT "coral_user@webhost" on the database, the database host "dbhost" needs to lookup the domain name "webhost".  Typically the MySQL server would be internal and if you don't have any internal DNS servers, which is not entirely uncommon, this may not resolve correctly.

Reverse DNS also comes into play also.  Let's say "webhost" is 192.168.1.15.  When "webhost" connects, "dbhost" will get the incoming IP address 192.168.1.15, but then MySQL will do a reverse-DNS lookup to see if this matches "webhost".  Reverse DNS can be slow.  More info:
https://dev.mysql.com/doc/refman/5.5/en/host-cache.html
https://www.percona.com/blog/2008/05/31/dns-achilles-heel-mysql-installation/

I think this either IP or hostname is going to have pros and cons.  I think your solution is fine, although I think ideally it should just have an option for the user to specify the value, but I understand that's going to be more work.  But thanks for looking into this!

**Comment by jcuenod** [comment]
Okay, I spent a bit of time trying to understand this and I see that there are DNS lookup issues in mysql (and, no doubt, maria).

I tried granting on an ip address though:

    GRANT ALL ON Foo TO 'Fred'@'127.0.0.1' IDENTIFIED BY 'Baz';

And then logging in:

```
$ mysql -u Fred -h localhost -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'Fred'@'localhost' (using password: YES)
$ mysql -u Fred -h 127.0.0.1 -p
Enter password: 
Welcome to the MariaDB monitor.
```

By contrast, a `GRANT` on `@localhost` allowed logging in with the IP or with the host name.

I thought that turning on `skip_name_resolve` would change things but `user()` always returned `localhost` for me.

I thought that logins may be affected by `skip_name_resolve` (to turn this on, you just add the line `skip-name-resolve` to `[mysqld]` in `my.cnf` [in my case `/etc/mysql/my.cnf` - and to test that you can use `show variables;`). It didn't make a difference though (cf. [howto-turn-off-mysql-reverse-dns-lookup-to-speed-up-response-times/](https://developer.sugarcrm.com/2012/01/10/howto-turn-off-mysql-reverse-dns-lookup-to-speed-up-response-times/) - it's worth noting that this was posted in 2012, a comment does mention that mysql should be caching host names so the speed issues should not exist and I must admit I'm not sure I know what's going on here but in short, I'm not convinced ip addresses are the way to go here).

So the **conclusion** to this ever growing comment:
1. we can implement an "advanced" option but I can't prepopulate it with a suggestion and it just gives users room to break things or
1. we can just grant based on the suggestion above and then expect advanced users to manage more complex grants manually.

I do actually see pros and cons for both of these options so I'm keen to hear from you both...

**Comment by t4k** [comment]
I’ve tested this within the context of all the code in #168 and I don’t think it is working yet.

I’m using AWS EC2 with a database on RDS (another host). I can get through the installer, but then trying to access any of the modules, like resources, licensing, auth, I get errors like:

`Access denied for user ‘coral_user’@’%’ to database ‘testcoral_auth’ in /var/www/testcoral/auth/admin/classes/common/DBService.php on line 48`

Examining the `mysql` database, I have a `coral_user` for my real CORAL installation and in the `user` table it has entries for `localhost` and `%`. The new installation added an entry for the host of the current installation, `test.coral.example.net`.

In the `db` table for my real CORAL installation I have entries for my `coral_*` tables on hosts `%` and `localhost`, but on my new `testcoral_*` tables I only have host entries for `test.coral.example.net`. Without the `%` and/or `localhost` entries the connection doesn’t work because the hostname not the same as the RDS host that MySQL is actually running on.

**Comment by jcuenod** [comment]
Hmm, thanks @t4k - I had forgotten about this issue. I was hoping for comment from either @jeffnm or @jamesrf but I will go ahead with the solution above:

    $db_user_result = $db->processQuery("SELECT SUBSTRING_INDEX(USER(),'@',-1)");

**Comment by jeffnm** [comment]
I'm sorry, I didn't give you my opinion. 

> 1. we can implement an "advanced" option but I can't prepopulate it with a suggestion and it just gives users room to break things or
> 2. we can just grant based on the suggestion above and then expect advanced users to manage more complex grants manually.

I too see pros and cons to both approaches. I think an advanced option, even one that is not pre-populated, but is well labeled is better though. That's just my opinion.

**Comment by jcuenod** [comment]
@jeffnm Hmm, I see that I missed your comment this morning - this fix was just waiting for a commit on my computer for the last few weeks so I just pushed it today. It's following (2) though which is not what you're suggesting.

**Comment by jeffnm** [comment]
@jcuenod No problem. Thanks for including a fix.
