### ISSUE TITLE
Resource Module -> Helpful Links position

### ISSUE THREAD

**Issue by techsvcslib** [Coral-erm/Coral#178]
The Helpful Links area within a resource record does not position properly in the UI, overlapping important content. See attached screenshot for illustration.
![2017-02-26_12-02-37](https://cloud.githubusercontent.com/assets/3106487/23342198/bdccac14-fc1b-11e6-8226-ef8a25f79f16.gif)

**Comment by jeffnm** [comment]
This seems to be a result of the left side menu taking up a bit more space in the allotted center area. 

One quick but messy way to solve this would be to add `margin-right: -115px;` to the rightPanel. 
![screen shot 2017-02-27 at 3 45 18 pm](https://cloud.githubusercontent.com/assets/651304/23381387/db29b8c2-fd03-11e6-8644-146f09b94bd6.png)
