### ISSUE TITLE
Tell the user to do a backup

### ISSUE THREAD

**Issue by jcuenod** [Coral-erm/Coral#189]
This is just to record another milestone before 2.0:
The installer needs to tell the user (1) to fully update and (2) to do a backup.

**Comment by jeffnm** [comment]
@jcuenod Did you add this into your #186 request?

**Comment by jcuenod** [comment]
No I haven't yet - do you want me to add it in a new pull request though?

**Comment by jeffnm** [comment]
If the only change you are making is new text on one of the pages, don't bother, just add it to the open one.  If you need to make anything more involved than that, please do it from a new pull request.

**Comment by jcuenod** [comment]
You should check the wording

**Comment by jeffnm** [comment]
It looks good. Thank you.
