### ISSUE TITLE
Error on routing screen - ResourceStep missing dateArchive

### ISSUE THREAD

**Issue by jamesrf** [Coral-erm/Coral#190]
In Resources, I click on a resource and click "Routing", I get this error:

Fatal error: Uncaught exception 'Exception' with message 'There was a problem with the database: Unknown column 'archivingDate' in 'order clause'' in /var/www/html/resources/admin/classes/common/DBService.php:39 Stack trace: #0 /var/www/html/resources/admin/classes/common/DBService.php(73): DBService->checkForError() #1 /var/www/html/resources/admin/classes/domain/Resource.php(1954): DBService->processQuery('SELECT * FROM R...', 'assoc') #2 /var/www/html/resources/ajax_htmldata/getRoutingDetails.php(9): Resource->getResourceSteps() #3 /var/www/html/resources/ajax_htmldata.php(24): include('/var/www/html/r...') #4 {main} thrown in /var/www/html/resources/admin/classes/common/DBService.php on line 39

Looking here, this is the query being run:
https://github.com/Coral-erm/Coral/blob/b200fae47/resources/admin/classes/domain/Resource.php#L1952

However, it doesn't appear that resourceStep has an archivingDate:
https://github.com/Coral-erm/Coral/blob/b200fae47/resources/install/protected/install.sql#L471

I am using master (at 0fb5c34ecdb)

**Comment by veggiematts** [comment]
archivingDate was introduced by #117 , which has been merged.
The database update is here: https://github.com/Coral-erm/Coral/pull/117/files#diff-e1bbe4cec073

**Comment by jeffnm** [comment]
@veggiematts  For some reason that change to ResourceStep did not make it into the 2.0 update or install sql files.  That needs to be fixed before the 2.0.0 release.

**Comment by jeffnm** [comment]
#193 fixes this for the upgrade but is missing some of the starter data for fresh installs.
