### ISSUE TITLE
Update Usage Statistics module to support COUNTER R5

### ISSUE THREAD

**Issue by mdk2126** [coral-erm/coral#194]
Given the significant changes between COUNTER R4 and R5, significant planning and work will be required, especially if the module is to handle both kinds of data.  R5 reports will be required for COUNTER compliance as of January, 2019.

https://www.projectcounter.org/counter-release-5-draft-code-of-practice-consultation/

**Comment by jeffnm** [comment]
With no associated PRs for this work, this is getting bumped to 2.2.0 milestone.

**Comment by dineshranjan** [comment]
Since the COUNTER 5 is live now, is there any developments happening in usage module for future releases?

**Comment by jzairo** [comment]
It would be GREAT to have Counter 5 added. Release 5 is the current Code of Practice and the requirement for COUNTER compliance effective from [January of 2019](https://www.projectcounter.org/code-of-practice-five-sections/abstract/).

**Comment by rtatterson** [comment]
This was merged into last release so closing this ticket.
