### ISSUE TITLE
Consolidate Independent Common Conf Files

### ISSUE THREAD

**Issue by jcuenod** [Coral-erm/Coral#198]
Right now we have two independently growing common conf files: `/admin/configuration.ini` and `/common/configuration.ini`. I think this is a reasonable requirement to add to the 2.0.0 release. I have been building the `common` one in the installer, @tuxayo has been building the `admin` one for tests (cf. https://github.com/Coral-erm/Coral/commit/00ad28b759d6fe1356712f0ecf1fe4d74d72492e).

I'm 70% of the way to a solution but I just don't want to forget about this while it's on the backburner.

**Comment by jeffnm** [comment]
@jcuenod What kind of timeline are you looking at to get this implemented? If this is going in the 2.0.0 release, we need it pretty soon.

**Comment by jcuenod** [comment]
Pretty soon...

**Comment by jcuenod** [comment]
If @t4k reviewed this commit: https://github.com/Coral-erm/Coral/pull/186/commits/0be52cffa8dba7f6ec2a347204227535118f1b38 (it has already been merged in), then this issue can be closed.

**Comment by jeffnm** [comment]
Thanks. I was wondering.
