### ISSUE TITLE
Fix link on webpage for Basic Install Documentation

### ISSUE THREAD

**Issue by infoseek1** [Coral-erm/Coral#20]
Technical Documentation and Install Guide for all module  on http://coral-erm.org/documentation/
Links to https://github.com/ndlibersa/CORAL-Main/wiki/CORAL-Technical-Documentation  

Should it  link to https://github.com/Coral-erm/Coral/wiki/CORAL-Technical-Documentation  ?

**Comment by jeffnm** [comment]
@scottvieira I think this is a documentation issue, so I'm assigning it to you. Do you want a documentation label that we could assign to Github Issues like this?

**Comment by scottvieira** [comment]
@jeffnm Yes, I think creating a documentation label is a good idea.

**Comment by scottvieira** [comment]
@infoseek1 I fixed this link.  Thanks for reporting this.
