### ISSUE TITLE
Ability to Delete a a Platform from the Usage Statistics Module 

### ISSUE THREAD

**Issue by infoseek1** [coral-erm/coral#202]
Currently there doesn't appear a way to delete a Sushi Client from the Usage Statistics Module (version 1.2)

**Comment by jeffnm** [comment]
Thanks for reporting this. Do you view this as a failing of the current system or as something you'd like to see eventually but don't consider essential to the current function?

**Comment by infoseek1** [comment]
I consider it a failing, it would be good to have delete function available to Admins, or maybe and archive function similar to archiving.

**Comment by jeffnm** [comment]
Thanks! I've added a bug label, and hopefully the Usage Statistics module will get some love soon.

**Comment by jzairo** [comment]
Agreed, if someone has uploaded a test, it would be nice to have an option delete for Admins.
