### ISSUE TITLE
database upgrade path from 2.0-beta to 2.0.0

### ISSUE THREAD

**Issue by t4k** [Coral-erm/Coral#206]
We’ve got data in an installation of 2.0-beta and I was wanting to use a copy of that installation to test some of the outstanding pull requests. I’m having trouble updating to the latest development code and having the database work correctly. (I am only referring to the resources database at this point, but the idea is probably valid across all modules.)

I tried running the `update_2.0.0.sql` file against the `coral_resources` database and got the error:
> ERROR 1054 (42S22) at line 32: Unknown column ‘fundName’ in ‘field list’

I think this file is to actually upgrade from the 1.x version of CORAL, so that attempt is misguided anyway.

Is an upgrade option a possibility for people that started with 2.0-beta? I’m willing to help think this through, but I don’t know the history of how all these `update_*.sql` files and the installer have worked in the past to ensure schema changes are accounted for as we are developing CORAL.

I really think an automated update/upgrade process should be part of the installer if it can be.

**Comment by jeffnm** [comment]
When making the unified installer, the decision that we made was to only upgrade from 1.x to 2.0 and then when there is a 2.0.1 or a 2.1 release that will upgrade from 2.0.  There is no path to upgrade from the 2.0 Beta, but the 2.0 Beta is marked as a beta and not for production. You should be able to simply replace the code in 2.0 Beta with the code with code from the pull requests, assuming the pull request didn’t include any database changes. If it does, then you're out of luck and will need to run the database change manually or rerun the upgrade from 1.x with the new changes included.  

New SQL is supposed to get added into the install.sql and into the update-NextReleaseNumber.sql file and then we have to add a section to the /module/install/module.php file to indicate that there is a new version and what dependencies it has.

If you have some suggestions about how to support upgrading from the 2.0 Beta, that's great. The only way I can think to do that with the existing system is to make the 2.0 Beta release actually have been 2.0 and then do a 2.0.1 release with the new SQL changes that were not included in the beta. This would bring both the 1.x people and the 2.0 beta up to 2.0.1 

@jcuenod do you want to comment on upgrading from our pre-release releases? Is there some other way of doing it that I'm missing?

**Comment by t4k** [comment]
Looking at this more, the db changes between 2.0-beta and now are only one field added, so not a big deal.

I never used 1.x so it wasn’t completely clear how this had worked in the past.

I’m sure I’ll learn more about the existing process as I continue to get more involved and as the project keeps making releases, so I’ll speak up when I have any new ideas.

**Comment by jcuenod** [comment]
I'm assuming that people using the beta release are more dev oriented - if that's the case, I would create sql files to run to do those small changes and then provide a sample common config file and just create it manually. That really assumes a relatively high degree of technical knowledge so if there are people in the wild running the beta, that's not what I would recommend to them.

**Comment by doug-hahn** [comment]
We have been running the BETA in production since its release.  I will concur that if people ran the beta in production then they should just be able to do the sql upgrade manually with some direction.

**Comment by jeffnm** [comment]
This has been addressed with a `2.0-beta-to-rc-manual.sql` file for the resources module and we do not anticipate further database changes between 2.0-rc and 2.0.0. If users need to go from 2.0-beta to the 2.0.0 we can tell them to use the same sql file. 

All other users can use the automated installer and upgrader.
