### ISSUE TITLE
Pages not working loading/

### ISSUE THREAD

**Issue by weepsie** [Coral-erm/Coral#220]
sorry if this is the wrong place, but the old listserv is gone, and I've had bounce backs from the contact form.

I've coral running here on AWS for a test - 

http://54.202.114.161/coral/

When try to login to anything I get a http 500 error. I am not sure if it's the .htaccess file or a permissions issue, and I'm at a loss coming from a non technical background. I'm guesssing it's a simple step I'm missing somewhere in the installation or preinstallation

**Comment by t4k** [comment]
So after you log in you are getting the 500 errors?

Is there any way you can post the Apache log file output you receive on that page load?

**Comment by weepsie** [comment]
I can only get as far as any of the login screens for resources, licensing, etc. It's why I am assuming it has something to do with my authentication. 

I have it running locally on xammp too, and it works but with a boat load of PHP errors.

This is all that I have in my error log file.

- script '/var/www/html/command.php' not found or unable to stat

- PHP Notice:  Undefined index: orderBy in /var/www/html/coral/resources/admin/classes/domain/Resource.php on line 805, referer: http://54.202.114.161/coral/

- PHP Notice:  Undefined index: page in /var/www/html/coral/resources/admin/classes/domain/Resource.php on line 805, referer: http://54.202.114.161/coral/

- PHP Notice:  Undefined index: recordsPerPage in /var/www/html/coral/resources/admin/classes/domain/Resource.php on line 805, referer: http://54.202.114.161/coral/

- PHP Notice:  Undefined variable: currentPage in /var/www/html/coral/resources/index.php on line 32, referer: http://54.202.114.161/coral/

- PHP Fatal error:  Call to undefined method mysqli_stmt::get_result() in /var/www/html/coral/auth/admin/classes/common/DBService.php on line 131, referer: http://54.202.114.161/coral/auth/?service=/coral/resources/
-

**Comment by remocrevo** [comment]
That last line means you need the mysqlnd driver. This link should give you instructions for installing it on Windows:

http://php.net/manual/en/mysqlnd.install.php

Let us know if that doesn't solve your problem.

**Comment by weepsie** [comment]
I am trying it on a few platforms. But I did take your advice and added the myqlnd driver in ubuntu and that now works. 

I can log in to all modules now so can hopefully now convince someone we should install it for the institution so we can use it.

Thanks for the help as I realise this would have been a question better asked on the list serv, but am waiting to get on that.

**Comment by remocrevo** [comment]
No problem. I'll close this issue for now.  If you have more questions and are not ready to join the email list, feel free to open another issue here.
