### ISSUE TITLE
Resource Module -> Helpful Links position

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/coral#249]
Unfortunately it appears that a previously resolved issue (see #178) has reappeared in 2.0.1. This needs to be fixed asap. Attached is a screenshot.
![2017-06-26_10-12-12](https://user-images.githubusercontent.com/3106487/27546413-5049b844-5a58-11e7-9df6-132ef90e5e49.gif)

**Comment by jeffnm** [comment]
It looks like the CSS workaround was applied to the resource URL, but not the Alt URL.
