### ISSUE TITLE
Incorrect download format for Usage Reports reports

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/coral#254]
When users run a report in the Usage Reports module, an icon appears to indicate the report can be downloaded in an Excel-compatible format (either .xls or .csv). Currently, though, the actual output format is HTML and does not include a file extension or anything like that, and the file cannot be properly read or imported into Excel.

**Comment by rtatterson** [comment]
I'm no longer seeing this issue. Report downloads include TSV and CSV.

**Comment by sekjal** [comment]
Seeing this issue today, running CORAL 2020.09
