### ISSUE TITLE
Cancel button when reviewing SUSHI Import Confirmation doesn't work as expected

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/coral#255]
When retrieving a report via SUSHI, if the retrieval is successful, it is placed in the Outstanding Import Queue where users can then click on the "View to Process" link to review the data. After clicking on that link, users next see the SUSHI Import Confirmation screen. If users decide there is a problem with the data at this stage and want to cancel the import by clicking on the cancel button, a popup dialog window appears asking (at least, in the most recent version of the Safari browser for Mac), "Are you sure you want to send a form again?" with the option to either cancel or send. The expected result should be that when the cancel button is clicked on the SUSHI Import Confirmation screen, they are returned to the main SUSHI Administration screen. See attached screenshot for an example of the problem.

NOTE: If loading a stats file manually, there is a similar import confirmation screen, but the cancel button works as expected there.)

(
![2017-07-20_17-21-22](https://user-images.githubusercontent.com/3106487/28441533-e23c04ca-6d70-11e7-96fb-793d51b78d45.gif)

**Comment by andyp-uk** [comment]
I believe this issue was addressed in PR #660
