### ISSUE TITLE
Change the capitalization of this GitHub organization and repository

### ISSUE THREAD

**Issue by t4k** [coral-erm/coral#280]
Would anyone be opposed to changing the capitalization of our GitHub organization and repository to “coral-erm” and “coral” respectively? Since CORAL is an acronym it might be misleading or detract from the brand that these two strings are capitalized this way. I would go with all lowercase instead of all uppercase for readability and easier typing.

I have looked into the consequences of doing this: https://help.github.com/articles/renaming-an-organization/ and https://help.github.com/articles/renaming-a-repository/

I do not think what I want to do is as drastic as those articles warn against, because it is just a case change, not a complete rename. While I know that paths after the domain on the web can technically be case-sensitive, it does not seem to matter on GitHub. I tried to create a new “coral-erm” organization and it said the name was taken. I have also typed in https://github.com/coral-erm/coral and https://github.com/CORAL-ERM/CORAL to my browser and they both redirect to our current repository. This means existing links would likely continue to work wherever we have them on the web and we can change them in time. I can even clone the repository on the command line using the lowercased version of the URL so I do not think existing remotes would be affected.

**Comment by t4k** [comment]
I should note that I was only referring to the URL in this issue. We should probably use “CORAL-ERM” and “CORAL” for the display names.

**Comment by techsvcslib** [comment]
+1

Steve

On Aug 23, 2017, at 12:18 PM, Tommy Keswick <notifications@github.com<mailto:notifications@github.com>> wrote:


I should note that I was only referring to the URL in this issue. We should probably use “CORAL-ERM” and “CORAL” for the display names.

**Comment by scottvieira** [comment]
Works for me.  Documentation can be changed too for consistency.

**Comment by remocrevo** [comment]
I support this change.  Thanks for the thorough investigation, Tommy.

Remington

--
Remington Steed
Electronic Resources Specialist
Hekman Library, Calvin College
http://library.calvin.edu/

**Comment by t4k** [comment]
Shall I consider consensus reached?

**Comment by techsvcslib** [comment]
I think so.

Steve

On Sep 1, 2017, at 11:10 AM, Tommy Keswick <notifications@github.com<mailto:notifications@github.com>> wrote:


Shall I consider consensus reached?

**Comment by t4k** [comment]
Just a heads up. I will do this tomorrow, September 6.

**Comment by paulocoghi** [comment]
@t4k How did you do it?
