### ISSUE TITLE
Worklow edit : wrong button "add" instead "X"

### ISSUE THREAD

**Issue by sbouis** [coral-erm/coral#281]
Hello,
just to mention that there's a small issue in workflow edit : when we add a workflow step, it appears in the step list but in the right end, the button stays as "add" instead to display a red cross for "remove".

**Comment by veggiematts** [comment]
Hi,

I can't reproduce the problem on master. Could you perhaps attach a screenshot please ?

**Comment by sbouis** [comment]
Here is a copy from the demo website. https://coraldemo.library.tamu.edu/resources/admin.php
The button is wrong when you add a step, after saving the workflow, it's ok.

![image](https://user-images.githubusercontent.com/31436815/29914290-479ac224-8e38-11e7-940b-baa69a21154c.png)

**Comment by veggiematts** [comment]
My bad, I was looking at the workflow edition on a resource, not in admin.
This occurs in master. It is an issue indeed.

**Comment by veggiematts** [comment]
This was broken by this diff: https://github.com/Coral-erm/Coral/commit/90af125b8aa56645496caddef0f65161f34268a6#diff-066f859e72c7ca6c7c1009d58783e513L155

So either we switch back to the image-button or we change the js in resources/js/forms/workflowForm.js to change from the add button to the remove image when adding a step.

**Comment by veggiematts** [comment]
Since i'm not a huge fan of image-buttons, here's a fix that allows to keep the real "Add" button.
