### ISSUE TITLE
role of an organisation

### ISSUE THREAD

**Issue by PaulPoulain** [coral-erm/coral#29]
In the org module, when you create/update an organization, you can select the role(s) it can have.
![Chose role](https://cloud.githubusercontent.com/assets/4696271/14881175/271545b0-0d33-11e6-86ef-ba5a3a8d0946.png)

In the resources module when you create/update a resource and attach an organisation, once you've chosen the role, the auto-complete does not limit the results to orgs that can have the selected role
![filter by role](https://cloud.githubusercontent.com/assets/4696271/14881244/647aaabc-0d33-11e6-9982-00be64d89be1.png)

**Comment by benheet** [comment]
Does anyone use the org role within the org module to filter/search for organizations? I wonder if the org role is only relevant within the context of the resource or license, and if so maybe it doesn't need to be in the org module at all. thoughts?

**Comment by techsvcslib** [comment]
We don’t currently use it but I think it’s helpful to have.

Steve

**Comment by scottvieira** [comment]
I agree with Steve.  I haven't use this too much, but I have used it for housekeeping purposes before.  For example, if I am trying to list and update all my consortium organizations.

**Comment by benheet** [comment]
I ask because if we leave it in the org module AND filter the auto-suggest within the Resources module to only show orgs that match a certain role it will require the user to actively keep the assignments in the org module up to date. I would then lean towards not limiting the scope of the auto-suggest feature.

**Comment by scottvieira** [comment]
We are pretty thorough in setting the roles for our organizations so this wouldn't be a problem for us, but I can see what you are saying.  Would it be possible to filter by role and undefined role so that auto-suggest feature would always contain both?  So for those libraries that don't set roles it won't matter, but for those that do it will.

**Comment by benheet** [comment]
I'd be ok with just leaving it as it is now. Its an auto-suggest feature pulling from several hundred org records and that's not much. if it was pulling results back from several thousand, and i was having problems with multiple irrelevant hits, then i'd filter but i'm comfortable with how it works now.

**Comment by techsvcslib** [comment]
Agreed — leave as is for now.

Steve

**Comment by PaulPoulain** [comment]
I agree with scott: we could have a behaviour that says: "if no role selected, it mean 'all roles' selected". So there would be no change for libraries not needing it, and a change for libraries entering the roles. Ben & Steve: would you object this behaviour ?

It's an important behaviour for large consortia, with many librarians managing ER, from various libraries. In the long term I also think this "org role" can be extended to filter more things.

And I also think the "role filtering" should be extended to other areas of Coral.

**Comment by jeffnm** [comment]
@techsvcslib @PaulPoulain I'm trying to figure out whether this is an issue that I should tentatively mark for 2.1.0 beta milestone or close as won't fix. I'm afraid I can't draw a conclusion from the conversation thus far. What's your current consensus?

**Comment by PaulPoulain** [comment]
@jeffnm I fear we haven't reached a consensus (yet). I'm still in favor of my idea: if the librarian chose a role before searching, filter on libraries having this role or no role ("no role" being considered as "all roles")

**Comment by jeffnm** [comment]
That makes sense to me. An "Any" role option would be pretty reasonable from my perspective.

**Comment by xsong9** [comment]
This needs further discussion. Let's target it for a later release.

**Comment by xsong9** [comment]
The original requester is no longer with CORAL, so close the issue now until any interests come up in the future.
