### ISSUE TITLE
Translatability of menus

### ISSUE THREAD

**Issue by PaulPoulain** [Coral-erm/Coral#30]
The tab menus, on the left, are not translatable
![tabs not translatable](https://cloud.githubusercontent.com/assets/4696271/14881325/c30c74b6-0d33-11e6-8310-0fb49da474de.png)

**Comment by benheet** [comment]
why is that? are they images?

**Comment by PaulPoulain** [comment]
I don't think they're images, I can select a part of the text with my mouse. I haven't investigated yet, but I suspect it comes from some javascript, and the lack of a _() on the text to translate (not sure though)
I haven't checked if SirsiDynix PR changes something, it could.

**Comment by bdroubay** [comment]
We have made everything translatable, with French translations for everything. We have changed all of the images to images plus translatable text, including the landing page.  We will be rolling out the changes this week starting with the landing page, then the auth module, followed by resources, licensing, organizations, usage, reports, and management.  The landing page is ready to commit and push to master -- we are just waiting on the green light.

**Comment by remocrevo** [comment]
@bdroubay From the CORAL-ADMIN email conversation, it sounds like you have the green light.

**Comment by PaulPoulain** [comment]
And thank you so much for taking care !!!

(note: next step to do with translation: merge the po files into a single one. I plan to take care of this asap, probably during the summer quiet weeks ;-) )

**Comment by PaulPoulain** [comment]
@bdroubay what's the status of your relooking/make menu translatable,... big patch ? We're ready to work on merging the .po file, and that will probably result in a conflict with your own work. any date for submitting & merging everything ?

**Comment by bdroubay** [comment]
I'm waiting on the French translations to come back for the Usage, Reports, and Licensing modules, so I can merge them. Hopefully by tomorrow, but I will check with the team in the UK tomorrow morning.

Brad

**Comment by jeffnm** [comment]
What's the status of this issue? Is it already fixed?

**Comment by PaulPoulain** [comment]
good catch. Just tested on tamu demo, it's fixed !
