### ISSUE TITLE
license display in the resource module

### ISSUE THREAD

**Issue by PaulPoulain** [coral-erm/coral#31]
The license is currently displayed in the "acquisition" tab. It is more logical to put it as a specific tab on the left (with acces, cataloging, contacts...)
![License link](https://cloud.githubusercontent.com/assets/4696271/14886653/2fa73d22-0d52-11e6-85dd-a7cb797078c0.png)

**Comment by benheet** [comment]
Right now there really isn't a lot of license information in the resource record. There is some convenience in having it displaying here with the other acq data, some of which is based on the content of the license. I am open to the discussion but not yet of the mind that this needs its own tab.

**Comment by PaulPoulain** [comment]
One of the ENH I'll propose soon is to have more than one order, to keep track of every year ordering. Each cost history being linked to an order.
With this ENH, it will make sense to have a specific tab for the licence, to keep the interface clean & easy to read

**Comment by techsvcslib** [comment]
Typically, at least here, there is one order that’s kept open year to year for subscribed e-resources, to which yearly invoices are attached, in our ILS (Ex Libris Voyager). I’m not sure I see why more than one order is needed in CORAL and I definitely am not sure why that makes having a separate license tab more important.

Steve

**Comment by PaulPoulain** [comment]
different countries, different behaviours I think. Here, there's one order every year (except when the university has signed a multi-year contract, but even in this case, there are specific things to record every year, for the accounting system).

Putting the license in a separate tab is to avoid having too many information in the same screen. Plus I find counter-intuitive to have the resource licence in the acquisition tab. The license is not related to the acq process isn't it ? 
for example: in France, for the most used/expensive resources, we have a national license, negotiated by Couperin. It differs from the acquisition, and pricing.

Other argument: in consortium environment, we can have, for a given year, libraries A, B and C, and the next year, A, B, and D. We want to keep track of this history.

**Comment by benheet** [comment]
something to consider; IF there was a separate license tab what might be on it other than the current fields? Would there be any value in having some of the license data from the license module displayed in a read only view within that tab (similar to how the Contacts tab can read in contacts information from the Org module). Just a thought. I'm still not sold on the necessity of a separate license tab but if it was to happen what would make it a worthwhile addition?

**Comment by techsvcslib** [comment]
I’ve been giving some thought to Ben’s questions. I’m not convinced that a new, separate license tab is necessary, either, and I still don’t understand why this ties into having multiple orders (BibLibre/Paul). If there were to be such a tab, one potentially useful thing to display from the license record in the licensing module is the effective date of the license. A direct link to the license document (in our case, a PDF) might be useful as well. But I think these are stretching it.

Steve

**Comment by techsvcslib** [comment]
Paul,

I understand about having too much information in one screen. I’d point out that licensing is very much a part of the acquisitions process in many libraries, though. I also think that there are ways we can explore to better manage the display of lots of information in various aspects of the UI. What I’m thinking of is a way to quickly expose/hide large chunks of information such as the cost history. Sort of like, expand/collapse with plus sign or something like that.

Steve

**Comment by PaulPoulain** [comment]
we're working on a v2 document presenting our plan to link Coral and an ILS. We realized that licenses are also attached to orders, as they can change regularly. So we have to think a little bit more about it.
Maybe something like adding dates of validity for a licence, and a status (attached to the license, one by one)

**Comment by sbouis** [comment]
Hello,
Regarding the displays of the Licence module link in the ressource module, my colleagues told me that when they work on a resource and want to check something on the licence, they can't remember in which tab you could find it.
They suggest me that it would be great if we could have this link in the "Helpful Links" box that appears, in particular, on the first "product" tab.
