### ISSUE TITLE
Automated testing with Travis CI

### ISSUE THREAD

**Issue by t4k** [coral-erm/coral#329]
I’m going to start working on getting Travis CI working with CORAL so that we can have every pull request tested as it comes in. This should work with our implementation of Codeception.

If anyone is interested in working on this with me, or learning how to do it (that’s where I’m at), let me know and we can collaborate. We can use the chat room on Gitter: https://gitter.im/coral-erm/coral

Also, any input on this is welcome!

**Comment by jcraitz** [comment]
Hi @t4k. Is this still something you're looking in to?  I'm interested.

**Comment by t4k** [comment]
@jcraitz I haven't touched it in a few months. I've had other projects and then we have been making the push for the 2.1 release. I'm definitely going to make it my focus after 2.1 is out so that we can streamline testing even further for this project. Glad to know you are interested!

**Comment by rtatterson** [comment]
Tommy is no longer working with CORAL SC so I am going to close this issue.
