### ISSUE TITLE
Coral Installer Failed

### ISSUE THREAD

**Issue by selimatmaca** [coral-erm/coral#331]
Hi,
I installed  Apache 2.4.18, Php7.0. , MySQL 5.7.20. I tested them and they all work. 

I am installing Coral v2.0.1. I started the web script from a browser, It brought me the page "Modules to Use" and then the page for  DatabaseUser, DatabasePassword and host . I filled those fields with the MySQL root/MySQL rootpassword and localhost

Now I am stuck with the message "CORAL Installer Failed".
I got no clue what I am doing wrong at this point. Please help.

**Comment by jeffnm** [comment]
The error message is just "CORAL Installer Failed"? With no other visible information?  

Could you check your apache error log to see if anything was reported there?  

If you reload the CORAL install page, does it still give you the "CORAL Installer Failed" message or does it load a different page?

**Comment by jcuenod** [comment]
That sounds like the installation page is having trouble sending data to your server.
How did you start the script?

(Apologies if this is obvious to you but just to cover the bases, if the url in your browser is something like `file:// ... ` rather than `http:// ...` the problem is just how you're connecting to CORAL)

**Comment by selimatmaca** [comment]
Hi,
If I reload the page, it brings the same error page "Coral Installer Failed".
I start the script by entering the ip address of the server from my laptops browser. I see the initial pages like what modules I want to install etc. I enter mysql root, password and host. After I click Next, it returns the error page.

In apache error.log file, I see the following error. 
PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/common/DBService.php


The whole error log is here:
[Tue Nov 21 09:54:59.491848 2017] [:error] [pid 4339] [client 10.50.95.43:52848] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/common/DBService.php:45\nStack trace:\n#0 /var/www/html/install/providers/get_db_connection.php(38): DBService->__construct(false)\n#1 /var/www/html/install/providers/have_database_access.php(163): {closure}(false)\n#2 /var/www/html/install/installer.php(281): {closure}(Array)\n#3 /var/www/html/install/installer.php(272): Installer->actuallyRunTest('have_database_a...', Array)\n#4 /var/www/html/install/installer.php(265): Installer->runTestForResult('have_database_a...', Array)\n#5 /var/www/html/install/installer.php(265): Installer->runTestForResult('db_tools', Array)\n#6 /var/www/html/install/installer.php(265): Installer->runTestForResult('auth', Array)\n#7 /var/www/html/install/installer.php(265): Installer->runTestForResult('modules_to_use_...', Array)\n#8 /var/www/html/install/index.php(112): Installer->runTestForResult('set_installed_v...')\n#9 /var/www/html/install/index.php(196): run_loop('INSTALL')\n#10 /var/www/html/index.php(4): require_once('/var/www/ in /var/www/html/common/DBService.php on line 45, referer: http://192.168.1.251/

**Comment by selimatmaca** [comment]
Finally, I solved the problem and installed the coral succesfully. Thanks.

Solution: 
I ran the following command on ubuntu terminal to install missing mysql package
sudo apt-get update
sudo apt-get -y install php7.0-mysql php7.0-mysqlnd

Restarted Apache
sudo systemctl restart apache2.service

and it works now.

**Comment by jcuenod** [comment]
Glad you got it sorted.
