### ISSUE TITLE
Editing Saved Resources

### ISSUE THREAD

**Issue by ozhansaglik** [coral-erm/coral#342]
Dear community,

I hope everyone is well. We have setupped Coral to our host and localhost. When saved a resource then did want to edit, we have encountered problems in our server. We could not face this problem in localhost. Enclosed are screenshots about this problem. Is there anything that we did miss?

Thanks for your contribution.

Özhan

![edit hata_host_server](https://user-images.githubusercontent.com/32630345/34815758-aefe8dda-f6c3-11e7-9da8-b089ad6932ea.jpg)
![edit hata_local](https://user-images.githubusercontent.com/32630345/34815759-af202288-f6c3-11e7-96ee-b0fd13ba9324.jpg)

**Comment by veggiematts** [comment]
Any error in the server logs ?

**Comment by ozhansaglik** [comment]
No, we did not have any error.

**Comment by ozhansaglik** [comment]
Hi all,

Is there anyone use CORAL in Windows server? Have you encountered any specific problems?

**Comment by ozhansaglik** [comment]
Dear all,

We solved the problem. We are using localhost for developping the Coral but when we select virtual host, the problem has gone. Thanks for your contribution.

Best

Özhan
