### ISSUE TITLE
ResourceAcquisition table not created

### ISSUE THREAD

**Issue by jeffnm** [coral-erm/coral#350]
As I noticed when testing #334 the ResourceAcquisition table is not in the upgrade or install sql for the resources module, and it should be in both for 2.1 or the resource module can't display resources on the main screen. References to it seem to have been introduced in 801c751

@veggiematts could you make sure all the database changes that are needed to support that code are in the install.sql file and in an upgrade file? I can't find reference to that new table in the sql, and I don't know if any other database changes were expected as part of that feature.

**Comment by veggiematts** [comment]
@jeffnm the upgrade file is here: `resources/install/protected/update_Orders.sql`
I'm not sure what's the current state of the installer (ie: if this file will be automatically processed on upgrade), but I'll look into it.

Also, I wasn't sure if the install.sql file should be updated only once upon new version release or on each PR. If it's on each PR, I'll gladly add the missing SQL to install.sql. Please let me know.

**Comment by veggiematts** [comment]
@jeffnm see #351 for the upgrade.
Let me know for a fresh install.

**Comment by jeffnm** [comment]
@veggiematts ah, thanks, I'm not sure why I didn't see that when I searched that directory. The file won't be automatically processed on an upgrade unless it's added to the `resources/install/resources.php` `2.1.0` case, but that's not a difficult change. 

For the fresh install, sometimes that needs to be different SQL than the upgrade, so it is probably worth including that at the time of the PR as well, rather than asking the releaser to convert update SQL into install SQL. 

#334 has upgrade cases for 2.1.0, so perhaps we can get that merged in before adding your `/install/protected/2.1.0/002-350.sql` file to the resources updater.
