### ISSUE TITLE
Resource module, no need to display the resourceID

### ISSUE THREAD

**Issue by PaulPoulain** [coral-erm/coral#36]
In a resource detail screen, we display the resourceID
Record ID:  227077

There's no reason for displaying this field, and no ID is not displayed in other areas of Coral (which is good)

**Comment by benheet** [comment]
The record ID displays in the url, correct? I have no objection to eliminating the record ID from the record display if nobody can identify a function for having it there.

**Comment by techsvcslib** [comment]
Agree with Ben.

**Comment by tuxayo** [comment]
It's also displayed in the different resources lists and it's one of the search fields.
![capture d ecran_2016-07-11_11-10-55](https://cloud.githubusercontent.com/assets/2678215/16725578/3228792c-4758-11e6-8702-aa13c857d6ed.png)

Should these two stay or be removed as well?

**Comment by PaulPoulain** [comment]
there's no reason to use this information. The useful id is the ISSN/ISBN -that should appear in the result list
