### ISSUE TITLE
Release Procedure

### ISSUE THREAD

**Issue by t4k** [coral-erm/coral#363]
During the last Steering Committee we discussed documenting the procedure for creating releases for CORAL.

With the upcoming 2.1.0 release we have an opportunity to document what we will do and what we did successfully and unsuccessfully.

I have started a wiki page at: https://github.com/coral-erm/coral/wiki/Creating-Releases

Assigning this at first to @xsong9 because she volunteered to draft an initial document.

**Comment by xsong9** [comment]
Here is my first draft.
https://docs.google.com/document/d/1y-OpbbCZjmoaRpPHQ58NZjEwf0c5Q9ZrensUVDwmNnE/edit

Please take a look and let me know if you have any comments.

**Comment by xsong9** [comment]
I notice I can't add a new project under the Projects tab. I have some ideas about using the project board here to manage releases. I'd like to create one, so you can all take a look. Is it a permission issue or something else?

**Comment by t4k** [comment]
@xsong9 I've added you to the Steering Committee group here, so I think that should do it.

**Comment by xsong9** [comment]
@t4k It does. Thanks, Tommy!

**Comment by scottvieira** [comment]
@xsong9 Great job in getting this started!

**Comment by jeffnm** [comment]
I added some comments to the linked doc, which was a great start.

Do we need a call to flesh it out the rest of the way?

**Comment by xsong9** [comment]
Thanks for all the comments, everyone! Keep sending your comments and I'll send out a call next week to flesh this out.

**Comment by PaulPoulain** [comment]
Just FYI, in case it's useful: the Koha community wrote a script that generates the release notes automagically. It's here: http://git.koha-community.org/gitweb/?p=release-tools.git;a=blob;f=bin/koha-release;h=d22f89663193f85120e7f6e757b0b36b60c48bc0;hb=HEAD

It retrieves all bugs in Git for a commits range. For this reason, it must be launched from the root directory of a Koha Git repository. The bugs descriptions are retrieved from bugzilla using BZ REST API. It also generates contributors & signers & sponsor list (using Git informations), and translation percentage per language. 

The script works on a range of Git commits. This range generally has to cover commits from the last released version to the current one. For example, if the current version to be published is 3.22.3, and the previous one was tagged v3.22.02, this would be a valid range: v3.22.02..HEAD.

The script is parametrized with a configuration file: C<etc/config.yaml>. See it for details. There is one Template Toolkit file used to generate the Markdown release notes file: C<etc/notes.tt>.

It's not usable as-is by Coral, but may be a start for our own release note generation.

**Comment by xsong9** [comment]
@PaulPoulain Great idea!  
As part of the release management procedure, I've created a project board to manage 2.1 beta release. 
https://github.com/coral-erm/coral/projects/1
We'll flesh this out at a conference call next week. I'll send out the conf call details later. 

Yan
