### ISSUE TITLE
SUSHI server registry link no more valid

### ISSUE THREAD

**Issue by PaulPoulain** [coral-erm/coral#375]
on the SUSHI parameters page (https://coraldemo.library.tamu.edu/usage/publisherPlatform.php?platformID=12429)
there's a link  "Visit the SUSHI Server Registry for information about adding your provider." (http://www.niso.org/workrooms/sushi/registry_server/) that is a 404.

**Comment by veggiematts** [comment]
What would be the correct URL? https://groups.niso.org/workrooms/sushi/registry_server/ ?

**Comment by PaulPoulain** [comment]
I think yes.

**Comment by calierik** [comment]
The registry link appears to be hosted here now: 
https://registry.projectcounter.org

From my download the pathname is: coral-2020.09\usage\ajax_htmldata.php
