### ISSUE TITLE
Use an icon for Add/Create/New

### ISSUE THREAD

**Issue by PaulPoulain** [coral-erm/coral#387]
We have an icon for modifying & deleting something:
![image](https://user-images.githubusercontent.com/4696271/37523487-67815d2a-2927-11e8-8737-d5182aebc06e.png)
We should have one for adding something, and it should be on the top/right (close to the title of what to be added. For example:
![image](https://user-images.githubusercontent.com/4696271/37523628-d3730574-2927-11e8-9f62-f197d1e41e92.png)

**Comment by PaulPoulain** [comment]
linked to #380

**Comment by veggiematts** [comment]
Implemented by #546
