### ISSUE TITLE
Make sure the Installer/Upgrader SQL is ready for the 3.0 Beta Release

### ISSUE THREAD

**Issue by jeffnm** [coral-erm/coral#394]
There are some SQL commands that are being run twice, once in the install, and then again during the subsequent "update" step that happens automatically during the install. 

New SQL from this point forward should only go in the numbered releases with incremental file names per #302 and #285. Since we are releasing 3.0.0 instead of 2.1.0, we need to fix those version numbers in the files and directories that have already been merged into development.

If you find any SQL that is not being applied properly, please comment or edit this issue to add it.

- [ ] The install SQL for the ebscoKbID https://github.com/coral-erm/coral/blob/a375c474f1e8633c7a6afd530b7d5207096da800/organizations/install/protected/install.sql#L115 is the same as https://github.com/coral-erm/coral/blob/a375c474f1e8633c7a6afd530b7d5207096da800/organizations/install/protected/2.1.0/003-334.sql#L1 but it should only occur in the version upgrade as that is expected to be applied even in the case of a fresh install.
- [ ] `/module/install/protected/2.1.0` folders need to be renamed to 3.0.0
- [ ] The `organizations.php`  and other modules installation providers need their 2.1.0 cases renamed to 3.0.0

**Comment by jeffnm** [comment]
#392 is now fixing the ebscoKbID column in both the install and update columns.

**Comment by jeffnm** [comment]
#402 is now open for the version changes. 

We still need to verify that all needed database changes have been added correctly to the SQL, but all that have will be installed/upgraded.

**Comment by veggiematts** [comment]
So #392 and #402 combined are the two PR needed to test this issue ?

**Comment by jeffnm** [comment]
Yes, both are needed.

**Comment by jeffnm** [comment]
I'd prefer not to merge them myself. Any chance you could merge them @t4k ?

**Comment by t4k** [comment]
Merged!
