### ISSUE TITLE
"Deutsch" displayed as default in select list

### ISSUE THREAD

**Issue by t4k** [coral-erm/coral#403]
When working off the current development branch, I have "Deutsch" as the selected option in the select list for the *Change language:* options throughout CORAL.

All the language strings are showing in English across all modules, so it is confusing that the select list is indicating German.

After selecting English it appears to get locked and sticks, but the initial value as Deutsch does seem to be incorrect.

Related to #388.

**Comment by veggiematts** [comment]
Probably related or the same as issue #103
