### ISSUE TITLE
Change email address to its plural form

### ISSUE THREAD

**Issue by xsong9** [coral-erm/coral#412]
This request was suggested by Sonia Bouis via coral-user listserv. 

In the Edit User Group window under Admin tab in Resources module, change Email Address to its plural form. To allow messages sent to multiple users, all email addresses need to be entered. The plural form will indicate users that multiple email addresses can be added. For a better user experience, maybe instruct users to add comma or space between each email address. 

Suggested change: 
Email Addresses (use comma and a space between each email address)

**Comment by veggiematts** [comment]
See PR #416
