### ISSUE TITLE
Getting Error after login of Successful installation

### ISSUE THREAD

**Issue by GaneshKandu** [coral-erm/coral#417]
### Getting error after login of Successful installation
- [type] => 1
- [message] => Call to undefined method mysqli_stmt::get_result()
- [file] => auth/admin/classes/common/DBService.php
- [line] => 131

 ### How i can install CORAL 2.0.1 only with single database using eight different prefix instead of creating eight different database ?

**Comment by veggiematts** [comment]
> Getting error after login of Successful installation

It seems that Mysqli is missing from your php installation. How you can install it and enable it depends on your operating system. You can have a look at http://php.net/manual/en/mysqli.installation.php

> How i can install CORAL 2.0.1 only with single database using eight different prefix instead of creating eight different database ?

I don't think this is possible for the moment.

**Comment by GaneshKandu** [comment]
i have mysqli installed
![img_20180416 1](https://user-images.githubusercontent.com/12833130/38801237-d5e7aa64-4158-11e8-9de4-55ccae84640e.png)

**Comment by veggiematts** [comment]
It is installed, but is it enabled? What does phpinfo(); say?

You should have a mysqli section in its output.

**Comment by GaneshKandu** [comment]
![img_20180416 2](https://user-images.githubusercontent.com/12833130/38803592-3bc7c21e-415f-11e8-9913-2ab77934ba97.png)

**Comment by veggiematts** [comment]
Seems related to issue #220

**Comment by GaneshKandu** [comment]
method mysqli_stmt::get_result() requires mysqlnd

**Comment by jeffnm** [comment]
>method mysqli_stmt::get_result() requires mysqlnd

Yes, mysqlnd is required for CORAL.

**Comment by GaneshKandu** [comment]
@jeffnm is any way i can use single database ?
