### ISSUE TITLE
SUSHI connectivity not working in 3.0 beta

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/coral#420]
When inputing correct SUSHI connection information (e.g. for EBSCOhost and ACS Publications) and then clicking on the "Test SUSHI Connection" link, the system appears to hang. The message displayed to the user is " [spinning circle] Running..." The exact same SUSHI connection information in 2.x works fine.

**Comment by jeffnm** [comment]
I found the following on the server from this attempt. 
```
[Tue May 08 17:15:38.196564 2018] [:error] [pid 1503] [client 10.10.251.144:54483] PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in /coral/usage/admin/classes/domain/SushiService.php:353\nStack trace:\n#0 /coral/usage/admin/classes/domain/SushiService.php(451): SushiService->soapConnection('http://www.niso...', Array)\n#1 /coral/usage/admin/classes/domain/SushiService.php(182): SushiService->sushiTransfer('JR1')\n#2 /coral/usage/ajax_processing.php(275): SushiService->runTest()\n#3 {main}\n  thrown in /coral/usage/admin/classes/domain/SushiService.php on line 353, referer: https://DOMAINNAME/usage/publisherPlatform.php?platformID=2&showTab=sushi
```
This indicates that the SOAP extension is missing: https://stackoverflow.com/questions/11391442/fatal-error-class-soapclient-not-found?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

@techsvcslib I've installed the soap extension on that server, can you try again?

**Comment by jeffnm** [comment]
Adding the SOAP extension and fixing directory permissions solved this issue.
