### ISSUE TITLE
Search results are not retained in Firefox

### ISSUE THREAD

**Issue by xsong9** [coral-erm/coral#427]
With Firefox, in Resources Home page, conducting a search by any parameter, clicking on one of the search results, then clicking on the back arrow in the browser, it did not go back to the search results with the selected parameter.  The search results appear to be retained in Chrom though. Can someone take look at this?

**Comment by veggiematts** [comment]
I might be wrong, but I have the feeling that it is more a browser behavior issue than something we have control over.

**Comment by sbouis** [comment]
It should be fixed by this one : https://github.com/coral-erm/coral/pull/621

**Comment by veggiematts** [comment]
Indeed. Closing this issue.
