### ISSUE TITLE
Dashboards results layout

### ISSUE THREAD

**Issue by scottvieira** [coral-erm/coral#432]
The layout of the dashboards results seems odd to me.  I'm not sure if this is bug or not.  Note that the left side menu seems to center in relation to the entire report instead of stay at the top of the screen.  See screenshots.  

![dashboardstatistics](https://user-images.githubusercontent.com/4641596/40492113-69074a94-5f35-11e8-8a56-8fdad078b275.PNG)

![dashboardsyearlycosts](https://user-images.githubusercontent.com/4641596/40492122-6d0f90c4-5f35-11e8-9637-4a5890e8b6d4.PNG)

**Comment by veggiematts** [comment]
Already fixed in #415 . Feel free to test it and leave a comment so it can be merged :)

**Comment by scottvieira** [comment]
@veggiematts I tested it and it worked fine.  Thanks.
