### ISSUE TITLE
Resource menu highlighting is broken

### ISSUE THREAD

**Issue by veggiematts** [coral-erm/coral#438]
Resource menu highlighting of the current selected tab is broken. Caused by PR #424 ?

**Comment by veggiematts** [comment]
Also broken in the Usage module.

**Comment by jeffnm** [comment]
Looks like it's related to : 
https://github.com/coral-erm/coral/blob/90000c1ed7bd60a168b0b355e368efa382732c7f/usage/directory.php#L31
https://github.com/coral-erm/coral/blob/90000c1ed7bd60a168b0b355e368efa382732c7f/usage/directory.php#L41-L51

The function is being called with lowercase spelling, so it doesn't match, and is consequently not getting the class changed. 

Options:
1. go back to lower case spellings and use CSS to capitalize again
2. change the places calling that function to pass in capitalized keys
3. make the comparison normalize capitalization before comparing

**Comment by veggiematts** [comment]
Option 3 would be good I think.
