### ISSUE TITLE
Add the final 1.x upgrade changes from old repos

### ISSUE THREAD

**Issue by jeffnm** [Coral-erm/Coral#44]
We need to apply the changes from the old standalone repos final 1.x releases so that we have the same base for the new upgrade processes. 

https://github.com/ndlibersa/

**Comment by remocrevo** [comment]
@jeffnm Good call.  In particular, we need to make sure all the changes from the security patch are applied to this new repo.  And we may want to make a more thorough practice of always adding "exit" after any use of "header()".

**Comment by jeffnm** [comment]
@remocrevo I think the security changes were already applied, but yes, we should make a habit of checking all use of "header()" to verify that they exit after.

**Comment by remocrevo** [comment]
@jeffnm Actually, I think there are two or three cases where I added "exit" lines that didn't get applied to this repo. I'll try to find them...

https://github.com/ndlibersa/management/commit/e3ad3b6c2481306f6f6c93dec6bd70703a720724

https://github.com/ndlibersa/usage/commit/bbc25261c29d66616c1468f9f7ffe7994a7867a2

https://github.com/ndlibersa/licensing/commit/71b958ac461e7fb3f0a96ac676b85cf2b0db9828

Contrast those with the commit to this repo:

https://github.com/Coral-erm/Coral/commit/2e01ad35174d3af76af9f5d095811a52dfad13b3
