### ISSUE TITLE
Missing Field in coral_resources.Resources

### ISSUE THREAD

**Issue by ubun2Junky** [coral-erm/coral#446]
Setup:
Docker:  Coral 3.0
PHP: 7.0
MySQL: 5.7

Was trying to setup the [alert scheduling](http://docs.coral-erm.org/en/latest/manual.html#resources-alerts-scheduling), when testing the `http://YOUR_PATH…/coral/resources/sendAlerts.php` script I got the following error:

`Fatal error: Uncaught Exception: There was a problem with the database: Unknown column 'subscriptionAlertEnabledInd' in 'where clause' in /var/www/html/resources/admin/classes/common/DBService.php:52 Stack trace: #0 /var/www/html/resources/admin/classes/common/DBService.php(91): DBService->checkForError() #1 /var/www/html/resources/admin/classes/domain/AlertDaysInAdvance.php(38): DBService->processQuery('SELECT DISTINCT...', 'assoc') #2 /var/www/html/resources/sendAlerts.php(37): AlertDaysInAdvance->getResourcesToAlert() #3 {main} thrown in /var/www/html/resources/admin/classes/common/DBService.php on line 52`

The AlertDaysInAdvance.php script contains the following query:
`$query = "SELECT DISTINCT resourceID
                                        FROM Resource
                                        WHERE ((DATE_SUB(currentEndDate, INTERVAL " . $this->daysInAdvanceNumber . " DAY) = CURDATE()) OR
                                        (currentEndDate = CURDATE()))
                                        AND subscriptionAlertEnabledInd = '1'";`

The query makes reference to the 'subscriptionAlertEnabledInd field.  When reviewing the table the script is accessing, there doesn't seem to exist a field with that name.
`mysql> describe Resource;
+-----------------------+---------------+------+-----+---------+----------------+
| Field                 | Type          | Null | Key | Default | Extra          |
+-----------------------+---------------+------+-----+---------+----------------+
| resourceID            | int(11)       | NO   | PRI | NULL    | auto_increment |
| createDate            | date          | YES  | MUL | NULL    |                |
| createLoginID         | varchar(45)   | YES  | MUL | NULL    |                |
| updateDate            | date          | YES  |     | NULL    |                |
| updateLoginID         | varchar(45)   | YES  |     | NULL    |                |
| archiveDate           | date          | YES  |     | NULL    |                |
| archiveLoginID        | varchar(45)   | YES  |     | NULL    |                |
| titleText             | varchar(200)  | YES  | MUL | NULL    |                |
| descriptionText       | text          | YES  |     | NULL    |                |
| statusID              | int(11)       | YES  | MUL | NULL    |                |
| resourceTypeID        | int(11)       | YES  | MUL | NULL    |                |
| resourceFormatID      | int(11)       | YES  | MUL | NULL    |                |
| currentStartDate      | date          | YES  |     | NULL    |                |
| currentEndDate        | date          | YES  |     | NULL    |                |
| resourceURL           | varchar(2000) | YES  |     | NULL    |                |
| registeredIPAddresses | varchar(200)  | YES  |     | NULL    |                |
| providerText          | varchar(200)  | YES  |     | NULL    |                |
| resourceAltURL        | varchar(2000) | YES  |     | NULL    |                |
| ebscoKbID             | int(11)       | YES  |     | NULL    |                |
+-----------------------+---------------+------+-----+---------+----------------+`

**Comment by jsavell** [comment]
'subscriptionAlertEnabledInd' appears to have been moved to the ResourceAcquisition table.

**Comment by jeffnm** [comment]
A fix has been merged and will be included in the next release.
