### ISSUE TITLE
Can't update or delete accounts

### ISSUE THREAD

**Issue by sbouis** [coral-erm/coral#450]
When we add an account on a resource with a autorized login, we don’t find any link to update it or to delete it.
![image](https://user-images.githubusercontent.com/31436815/42211120-0f6174a4-7eb3-11e8-9f86-41f3c6cce6f9.png)

**Comment by jeffnm** [comment]
This looks like it's an issue for the Contacts tab as well, where new contacts can be added but not edited or deleted.

**Comment by veggiematts** [comment]
@jeffnm I don't have any problems editing/deleting contacts on the development branch. Can you provide more informations?

**Comment by jeffnm** [comment]
@veggiematts my apologies, I was in a hurry when checking to see if this was a known issue and didn't notice that you had a pull request open for it already. I'll add the pull request to the patch 2.0.1 project as well. Thank you!

**Comment by jeffnm** [comment]
A fix has been merged and will be included in the next release.
