### ISSUE TITLE
Could not connect to the host

### ISSUE THREAD

**Issue by xanjib** [coral-erm/coral#456]
I'm trying to install CORAL 2.0.1 on Centos 7, I have installed all required software (PHP 7.0.30, MariaDB 10 , Apache/2.4.6 (CentOS). Next I untar CORAL 2.0.1 in the directory <html> and rename CORAL 2.0.1 folder as <coral>.

In the browser open <localhost/coral>, it shows CORAL Installer with all modules box checked. Next I click on <Continue Installing>. Then I enter Database User name: <root> and paasword for root and click on <Continue Installing>. Then I got the following messages.

Unfortunately we could not connect to the host.
Please review your settings.
---------------------------------------------------------------------------------------

Kindly help me please to complete installation.

**Comment by jeffnm** [comment]
The "Unfortunately we could not connect to the host." message means that MySQL isn't accepting the connection. Is your database on a special port or do you have firewalls blocking localhost access? Is the MariaDB service currently running?  

If you are successfully connecting, but have incorrect credentials, you'll instead see the
"Unfortunately, although we could find the database, access was denied." message.

**Comment by xanjib** [comment]
Thank you for your kind reply and support.
As per coral installation documents, I renamed and edited
<configuration.ini> file with host, database name, user name, password
details. Now I could open the Coral homepage <localhost/coral>. But when I
click any module image link on the main page, it shows nothing, only blank
page.

Could you please guide me how to proceed further.

Thanking you,
With regards,
sanjib,

**Comment by xanjib** [comment]
As per your advice, I remove everything and downloaded and extracted CORAL
folder and copied to /var/www/html and renamed as <coral>. Then on the
browser I enter <http://ip/coral> and found all the modules as checked,
then I click enter. In the next screen I enter mysql root user and password
for root user and click continue installing. Then I got the page with
<Trying to Read & Write configuration files>. I tried <chmod 777> for all
the folders, but still it asking <try again>. I have not changed any files
in the <coral> folder.

Cold you please tell me where I am wrong.
Regards,
sanjib

**Comment by jeffnm** [comment]
That's good! You were able to connect to your database. 

The file permissions warning is very, very common during installations. The installer wants to be able to write to the configuration files, but most of the time it doesn't have permission to do so. 

If you `chmod 777` the folders it suggests and click try again it should proceed. You can do them one at a time and see the list get shorter after each time you run the command and click "try again", or you can do it for all the directories at once. 

Once it writes all the configurations and finishes the installation, you'll see another bunch of warnings about the folders, saying it's not safe to leave them with 777 permission and requiring you to change them back to something a little more restricted before the installer will finish.

**Comment by xanjib** [comment]
I tried <chmod 777> for one folder at a time, but see no change. I have
also noticed that there is no <configuration.in> under admin folder,
instead there is <configuration_sample.in>. Should I need to rename all <
configuration_sample.in> as <configuration.in> ?

Regards,

**Comment by jeffnm** [comment]
No, the installer should be able to create the `configuration.ini` file for you, assuming it has permission to write to the directory. 

Can you run `ls -al` in your coral directory or in one of the modules? 
I'd like to see what permissions are actually set. It's possible you need to run `sudo chmod 777` on the directories if your user doesn't have permission to change permissions.  

Also, just to confirm, are you clicking the "Try again" button after making these permission changes?

**Comment by xanjib** [comment]
Following is the output of: ls -al
=================================================
[root@localhost coral]# ls -al
total 2620
drwxrwxrwx. 17 root root    4096 Jul 23 16:00 .
drwxr-xr-x.  3 root root      35 Jul 23 15:52 ..
-rw-r--r--.  1 root root 2520860 Sep 14  2017 anydesk-2.9.5-1.el7.x86_64.rpm
drwxrwxrwx.  8 root root    4096 Jul 23 15:52 auth
-rwxrwxrwx.  1 root root     360 Jul 23 15:52 codeception.yml
drwxrwxrwx.  2 root root     184 Jul 23 15:52 common
-rwxrwxrwx.  1 root root     556 Jul 23 15:52 composer.json
-rwxrwxrwx.  1 root root   76825 Jul 23 15:52 composer.lock
drwxrwxrwx.  2 root root     130 Jul 23 15:52 css
-rwxrwxrwx.  1 root root     360 Jul 23 15:52 .editorconfig
-rwxrwxrwx.  1 root root     265 Jul 23 15:52 .gitignore
-rwxrwxrwx.  1 root root     172 Jul 23 15:52 .htaccess
drwxrwxrwx.  2 root root    4096 Jul 23 15:52 images
-rwxrwxrwx.  1 root root    5075 Jul 23 15:52 index.php
drwxrwxrwx.  4 root root     181 Jul 23 15:52 install
drwxrwxrwx.  3 root root      56 Jul 23 15:52 js
-rwxrwxrwx.  1 root root    1094 Jul 23 15:52 LangCodes.php
drwxrwxrwx. 11 root root    4096 Jul 23 15:52 licensing
drwxrwxrwx.  7 root root      71 Jul 23 15:52 locale
drwxrwxrwx. 11 root root    4096 Jul 23 15:52 management
drwxrwxrwx.  9 root root    4096 Jul 23 15:52 organizations
-rwxrwxrwx.  1 root root    1152 Jul 23 15:52 README
drwxrwxrwx.  9 root root    4096 Jul 23 15:52 reports
drwxrwxrwx. 16 root root    4096 Jul 23 15:52 resources
drwxrwxrwx.  2 root root      24 Jul 23 15:52 templates
drwxrwxrwx.  7 root root     200 Jul 23 15:52 tests
-rwxrwxrwx.  1 root root    4844 Jul 23 15:52 TESTS.md
drwxrwxrwx. 13 root root    4096 Jul 23 15:52 usage
=====================================================

Regards,
sanjib,

**Comment by jeffnm** [comment]
Hmm. I'm not sure what to suggest then. That looks like the installer should be able to write the `common/configuration.ini` file (and the other configuration.ini files as well), assuming that 777 permission was recursively applied to everything in the coral directory as it appears. 

Can you take a screenshot of the message the installer is giving you? 

Another idea is to check your apache/php error logs and see if you are getting anything useful there.

**Comment by veggiematts** [comment]
First of all, regardless to the fact that it doesn't work, this is wrong :)

Coral files shouldn't belong to root, but rather to the web server user (usually www-data, but I think for CentOS it's apache).
You can fix that with this command:
<code>chown -R apache:apache *</code>

Then, having 777 on every file is also wrong, it means that every account on the system can read and write those files. You should have something like 644  for files (readable and writable by the webserver, and readable by others) and 744 for directories (enter, read and write for the webserver, read for others)

Then you can chmod 777 the config files if needed.

That being said, as @jeffnm suggested, looking at the error logs will probably be useful.

**Comment by xanjib** [comment]
Dear All,
Thank you for the suggestions, as already I left office, I shall try again
tomorrow.
With regards,

**Comment by xanjib** [comment]
Dear All,
I am still unable to resolve the issue. I have already reinstall the OS and
other dependant software and try to install Coral 3.0.0. But again the same
permission issue. Even after using chmod 777, it is not installing. Unable
to understand the error log file (Attached herewith for your information).

Following are the software installed:
centos-release-7-5.1804.el7.centos.2.x86_64
PHP 7.0.31 (cli) (built: Jul 17 2018 15:30:29) ( NTS )
Apache/2.4.6 (CentOS)
Server version: 5.5.56-MariaDB MariaDB Server
Coral 3.0.0

Kindly help me please.
With regards,

sanjib,

**Comment by xanjib** [comment]
I would also like to add that I have upgraded MariaDB from 5.5 to
10.1.34-MariaDB MariaDB Server.

**Comment by veggiematts** [comment]
I can't see your log file (I'm not sure attachments via email work on github)

**Comment by xanjib** [comment]
Attaching herewith the log file details.
====================================
[Wed Aug 01 14:33:31.534050 2018] [core:notice] [pid 18117] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 14:33:31.535720 2018] [suexec:notice] [pid 18117] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 14:33:31.549432 2018] [auth_digest:notice] [pid 18117] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 14:33:31.550972 2018] [lbmethod_heartbeat:notice] [pid 18117]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 14:33:31.554694 2018] [mpm_prefork:notice] [pid 18117] AH00163:
Apache/2.4.6 (CentOS) configured -- resuming normal operations
[Wed Aug 01 14:33:31.554747 2018] [core:notice] [pid 18117] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 14:33:38.756301 2018] [mpm_prefork:notice] [pid 18117] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 14:33:49.733783 2018] [core:notice] [pid 18152] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 14:33:49.735140 2018] [suexec:notice] [pid 18152] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 14:33:49.748471 2018] [auth_digest:notice] [pid 18152] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 14:33:49.749565 2018] [lbmethod_heartbeat:notice] [pid 18152]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 14:33:49.755894 2018] [mpm_prefork:notice] [pid 18152] AH00163:
Apache/2.4.6 (CentOS) configured -- resuming normal operations
[Wed Aug 01 14:33:49.755941 2018] [core:notice] [pid 18152] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 14:34:06.274982 2018] [mpm_prefork:notice] [pid 18152] AH00171:
Graceful restart requested, doing restart
[Wed Aug 01 14:34:06.289874 2018] [auth_digest:notice] [pid 18152] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 14:34:06.290989 2018] [lbmethod_heartbeat:notice] [pid 18152]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 14:34:06.291056 2018] [mpm_prefork:notice] [pid 18152] AH00163:
Apache/2.4.6 (CentOS) configured -- resuming normal operations
[Wed Aug 01 14:34:06.291066 2018] [core:notice] [pid 18152] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 14:36:07.704326 2018] [mpm_prefork:notice] [pid 18152] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 14:37:42.364209 2018] [core:notice] [pid 18814] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 14:37:42.365812 2018] [suexec:notice] [pid 18814] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 14:37:42.379677 2018] [auth_digest:notice] [pid 18814] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 14:37:42.381351 2018] [lbmethod_heartbeat:notice] [pid 18814]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 14:37:42.385032 2018] [mpm_prefork:notice] [pid 18814] AH00163:
Apache/2.4.6 (CentOS) configured -- resuming normal operations
[Wed Aug 01 14:37:42.385074 2018] [core:notice] [pid 18814] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 14:38:23.129925 2018] [mpm_prefork:notice] [pid 18814] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 14:38:24.201713 2018] [core:notice] [pid 18855] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 14:38:24.203089 2018] [suexec:notice] [pid 18855] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 14:38:24.216610 2018] [auth_digest:notice] [pid 18855] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 14:38:24.217747 2018] [lbmethod_heartbeat:notice] [pid 18855]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 14:38:24.221987 2018] [mpm_prefork:notice] [pid 18855] AH00163:
Apache/2.4.6 (CentOS) configured -- resuming normal operations
[Wed Aug 01 14:38:24.222046 2018] [core:notice] [pid 18855] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 14:39:46.003726 2018] [mpm_prefork:notice] [pid 18855] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 14:39:54.604110 2018] [core:notice] [pid 18927] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 14:39:54.605483 2018] [suexec:notice] [pid 18927] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 14:39:54.618927 2018] [auth_digest:notice] [pid 18927] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 14:39:54.620146 2018] [lbmethod_heartbeat:notice] [pid 18927]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 14:39:54.624270 2018] [mpm_prefork:notice] [pid 18927] AH00163:
Apache/2.4.6 (CentOS) configured -- resuming normal operations
[Wed Aug 01 14:39:54.624314 2018] [core:notice] [pid 18927] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 14:43:06.275533 2018] [mpm_prefork:notice] [pid 18927] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 14:43:07.356598 2018] [core:notice] [pid 19145] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 14:43:07.358031 2018] [suexec:notice] [pid 19145] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 14:43:07.371577 2018] [auth_digest:notice] [pid 19145] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 14:43:07.372787 2018] [lbmethod_heartbeat:notice] [pid 19145]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 14:43:07.380727 2018] [mpm_prefork:notice] [pid 19145] AH00163:
Apache/2.4.6 (CentOS) configured -- resuming normal operations
[Wed Aug 01 14:43:07.380774 2018] [core:notice] [pid 19145] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 14:43:14.827967 2018] [autoindex:error] [pid 19146] [client
202.141.81.5:37330] AH01276: Cannot serve directory /var/www/html/: No
matching DirectoryIndex (index.html) found, and server-generated directory
index forbidden by Options directive
[Wed Aug 01 15:28:52.259383 2018] [mpm_prefork:notice] [pid 19145] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 15:28:53.422802 2018] [core:notice] [pid 20484] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 15:28:53.434880 2018] [suexec:notice] [pid 20484] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 15:28:53.450274 2018] [auth_digest:notice] [pid 20484] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 15:28:53.451032 2018] [lbmethod_heartbeat:notice] [pid 20484]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 15:28:53.475809 2018] [mpm_prefork:notice] [pid 20484] AH00163:
Apache/2.4.6 (CentOS) PHP/7.0.31 configured -- resuming normal operations
[Wed Aug 01 15:28:53.475862 2018] [core:notice] [pid 20484] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 15:34:10.104537 2018] [mpm_prefork:notice] [pid 20484] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 15:34:11.314311 2018] [core:notice] [pid 20730] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 15:34:11.315886 2018] [suexec:notice] [pid 20730] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 15:34:11.347686 2018] [auth_digest:notice] [pid 20730] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 15:34:11.349096 2018] [lbmethod_heartbeat:notice] [pid 20730]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 15:34:11.520267 2018] [mpm_prefork:notice] [pid 20730] AH00163:
Apache/2.4.6 (CentOS) PHP/7.0.31 configured -- resuming normal operations
[Wed Aug 01 15:34:11.520325 2018] [core:notice] [pid 20730] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 15:36:45.227188 2018] [authz_core:error] [pid 20731] [client
202.141.81.5:40110] AH01630: client denied by server configuration:
/usr/share/phpMyAdmin
[Wed Aug 01 15:42:43.392047 2018] [mpm_prefork:notice] [pid 20730] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 15:42:44.487242 2018] [core:notice] [pid 20876] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 15:42:44.488835 2018] [suexec:notice] [pid 20876] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 15:42:44.520137 2018] [auth_digest:notice] [pid 20876] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 15:42:44.521566 2018] [lbmethod_heartbeat:notice] [pid 20876]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 15:42:44.550688 2018] [mpm_prefork:notice] [pid 20876] AH00163:
Apache/2.4.6 (CentOS) PHP/7.0.31 configured -- resuming normal operations
[Wed Aug 01 15:42:44.550724 2018] [core:notice] [pid 20876] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 15:44:08.060155 2018] [mpm_prefork:notice] [pid 20876] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 15:45:05.237604 2018] [core:notice] [pid 1199] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 15:45:05.308165 2018] [suexec:notice] [pid 1199] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 15:45:05.337530 2018] [auth_digest:notice] [pid 1199] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 15:45:05.339490 2018] [lbmethod_heartbeat:notice] [pid 1199]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 15:45:07.060121 2018] [mpm_prefork:notice] [pid 1199] AH00163:
Apache/2.4.6 (CentOS) PHP/7.0.31 configured -- resuming normal operations
[Wed Aug 01 15:45:07.060176 2018] [core:notice] [pid 1199] AH00094: Command
line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 01 17:06:51.114222 2018] [mpm_prefork:notice] [pid 1199] AH00170:
caught SIGWINCH, shutting down gracefully
[Wed Aug 01 17:06:52.204563 2018] [core:notice] [pid 15215] SELinux policy
enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Aug 01 17:06:52.205992 2018] [suexec:notice] [pid 15215] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Aug 01 17:06:52.234043 2018] [auth_digest:notice] [pid 15215] AH01757:
generating secret for digest authentication ...
[Wed Aug 01 17:06:52.235047 2018] [lbmethod_heartbeat:notice] [pid 15215]
AH02282: No slotmem from mod_heartmonitor
[Wed Aug 01 17:06:52.260160 2018] [mpm_prefork:notice] [pid 15215] AH00163:
Apache/2.4.6 (CentOS) PHP/7.0.31 configured -- resuming normal operations
[Wed Aug 01 17:06:52.260207 2018] [core:notice] [pid 15215] AH00094:
Command line: '/usr/sbin/httpd -D FOREGROUND'
======================================================================

Sorry for huge file.
