### ISSUE TITLE
Issue with Access Information in CORAL 3.0 Resources Module

### ISSUE THREAD

**Issue by rtatterson** [coral-erm/coral#462]
There appears to be a bug in the Resources module with editing access information. Data not being saved in the Access Information box when using "edit resource" but will save if using "edit access information."

**Comment by jeffnm** [comment]
It appears that the pencil and paper icon on the Access Information box is not passing in the resourceAcquisitionID, just the resourceID. We'll need to update that ajax Access Form request to match the "edit access information" link.

**Comment by jeffnm** [comment]
A fix has been merged and will be included in the next release.
