### ISSUE TITLE
Fatal Error exporting Resource search results to Excel

### ISSUE THREAD

**Issue by jeffnm** [coral-erm/coral#470]
This was first reported during troubleshooting of #468 and I have been able to reproduce it myself.

Steps to reproduce:
1. Open CORAL 3.0 Resources module
2. (Optional) On the Home page do a search.
3. On the Home page click the Excel Icon in the top right corner.  
4. The page will return a 500 error. 

The Apache/PHP logs will say 

> `Fatal error: Uncaught exception 'Exception' with message 'There was a problem with the database: Unknown column 'RPAY.priceTaxExcluded' in 'field list'' in /var/www/html/coral/resources/admin/classes/common/DBService.php:52 Stack trace: #0 /var/www/html/coral/resources/admin/classes/common/DBService.php(91): DBService->checkForError() #1 /var/www/html/coral/resources/admin/classes/domain/Resource.php(1058): DBService->processQuery('SELECT R.resour...', 'assoc') #2 /var/www/html/coral/resources/export.php(46): Resource->export(Array, 'TRIM(LEADING 'T...') #3 {main} thrown in /var/www/html/coral/resources/admin/classes/common/DBService.php on line 52`

**Comment by veggiematts** [comment]
I can experience the same problem on one of my instances, but it's RPAY.fundID that is missing.

This one can easily be explained: install.sql is wrong: table ResourcePayment should contain:

`  fundID int(11) default NULL,`

and not

`  fundName varchar(45) default NULL,`

@jeffnm could you paste a desc of your ResourcePayment table please ?

**Comment by jeffnm** [comment]
It looks like the fundID change is in https://github.com/coral-erm/coral/blob/master/resources/install/protected/2.0.0/001-000.sql (used to be update_2.0.0.sql before the sequential SQL update model in 3.0.0). 

Here's one of our ResourcePayment tables. 

```
+-----------------------+------------------+------+-----+---------+----------------+
| Field                 | Type             | Null | Key | Default | Extra          |
+-----------------------+------------------+------+-----+---------+----------------+
| resourcePaymentID     | int(11)          | NO   | PRI | NULL    | auto_increment |
| resourceAcquisitionID | int(11) unsigned | NO   | MUL | NULL    |                |
| fundID                | int(10)          | YES  | MUL | NULL    |                |
| selectorLoginID       | varchar(45)      | YES  |     | NULL    |                |
| paymentAmount         | int(10) unsigned | YES  |     | NULL    |                |
| orderTypeID           | int(10) unsigned | YES  |     | NULL    |                |
| currencyCode          | varchar(3)       | NO   |     | NULL    |                |
| year                  | varchar(20)      | YES  | MUL | NULL    |                |
| subscriptionStartDate | date             | YES  |     | NULL    |                |
| subscriptionEndDate   | date             | YES  |     | NULL    |                |
| costDetailsID         | int(11)          | YES  | MUL | NULL    |                |
| costNote              | mediumtext       | YES  |     | NULL    |                |
| invoiceNum            | varchar(20)      | YES  | MUL | NULL    |                |
| includeStats          | tinyint(1)       | YES  |     | NULL    |                |
+-----------------------+------------------+------+-----+---------+----------------+
```

**Comment by veggiematts** [comment]
> It looks like the fundID change is in https://github.com/coral-erm/coral/blob/master/resources/install/protected/2.0.0/001-000.sql (used to be update_2.0.0.sql before the sequential SQL update model in 3.0.0).

My bad, I thought that 2.0 updates were not processed by the installer. Must be a problem with my instance then.

> Here's one of our ResourcePayment tables.

priceTaxExcluded, taxRate and priceTaxIncluded are missing, but I can't see why, as they are in the default install.sql file. Is it on a fresh install or an updated one ?

**Comment by bmenk** [comment]
So is there a patch or workaround for the original error above? Or will fixing the additional errors reported by veggiematts solve all?

**Comment by veggiematts** [comment]
Well, there no patch to prevent the problem from happening, but you can add manually the missing databases fields. 

Just compare what's in your ResourcePayment table with this, and add the missing fields:

```
+-----------------------+------------------+------+-----+---------+----------------+
| Field                 | Type             | Null | Key | Default | Extra          |
+-----------------------+------------------+------+-----+---------+----------------+
| resourcePaymentID     | int(11)          | NO   | PRI | NULL    | auto_increment |
| resourceAcquisitionID | int(11) unsigned | NO   | MUL | NULL    |                |
| fundID                | int(10)          | YES  | MUL | NULL    |                |
| selectorLoginID       | varchar(45)      | YES  |     | NULL    |                |
| priceTaxExcluded      | int(10) unsigned | YES  |     | NULL    |                |
| taxRate               | int(10) unsigned | YES  |     | NULL    |                |
| priceTaxIncluded      | int(10) unsigned | YES  |     | NULL    |                |
| paymentAmount         | int(10) unsigned | YES  |     | NULL    |                |
| orderTypeID           | int(10) unsigned | YES  |     | NULL    |                |
| currencyCode          | varchar(3)       | NO   |     | NULL    |                |
| year                  | varchar(20)      | YES  | MUL | NULL    |                |
| subscriptionStartDate | date             | YES  |     | NULL    |                |
| subscriptionEndDate   | date             | YES  |     | NULL    |                |
| costDetailsID         | int(11)          | YES  | MUL | NULL    |                |
| costNote              | text             | YES  |     | NULL    |                |
| invoiceNum            | varchar(20)      | YES  | MUL | NULL    |                |
+-----------------------+------------------+------+-----+---------+----------------+
```

**Comment by bmenk** [comment]
Actually, there is no ResourcePayment table at all - should that not have been created by the upgrader either at the v1 > v2 or the v2 > v3 upgrade?  I guess I'm trying to understand the scope of the issue here. If the upgrader missed one entire table, are there any others I should check for that were supposed to be created that might have been missed? That's why I had asked about possibly running the sql queries the upgrader is supposed to call. Could the upgrade have just not called those sql queries at all for some reason?  Thanks. Bobb

**Comment by jeffnm** [comment]
@bmenk the ResourcePayment table existed in 1.x so it should exist on any version of CORAL. The question is if it got updated correctly to have the current column names. If you don't have that table at all, then you have bigger issues than this. I suspect you do have it, but are just overlooking it, because otherwise the error shouldn't be `Unknown column 'RPAY.priceTaxExcluded' in 'field list''` but something about the table `RPAY` being unknown. 

@veggiematts 
A fresh install of 3.0.0 on a test server results in a ResourcePayment table:
```
+-----------------------+------------------+------+-----+---------+----------------+
| Field                 | Type             | Null | Key | Default | Extra          |
+-----------------------+------------------+------+-----+---------+----------------+
| resourcePaymentID     | int(11)          | NO   | PRI | NULL    | auto_increment |
| resourceAcquisitionID | int(11) unsigned | NO   | MUL | NULL    |                |
| fundID                | int(10)          | YES  | MUL | NULL    |                |
| selectorLoginID       | varchar(45)      | YES  |     | NULL    |                |
| priceTaxExcluded      | int(10) unsigned | YES  |     | NULL    |                |
| taxRate               | int(10) unsigned | YES  |     | NULL    |                |
| priceTaxIncluded      | int(10) unsigned | YES  |     | NULL    |                |
| paymentAmount         | int(10) unsigned | YES  |     | NULL    |                |
| orderTypeID           | int(10) unsigned | YES  |     | NULL    |                |
| currencyCode          | varchar(3)       | NO   |     | NULL    |                |
| year                  | varchar(20)      | YES  | MUL | NULL    |                |
| subscriptionStartDate | date             | YES  |     | NULL    |                |
| subscriptionEndDate   | date             | YES  |     | NULL    |                |
| costDetailsID         | int(11)          | YES  | MUL | NULL    |                |
| costNote              | text             | YES  |     | NULL    |                |
| invoiceNum            | varchar(20)      | YES  | MUL | NULL    |                |
+-----------------------+------------------+------+-----+---------+----------------+
```

It looks like the https://github.com/coral-erm/coral/blob/97526009bd1035b5d293741195c90265726cacab/resources/install/protected/install.sql#L433
is the only place that column is added. For some reason it's not in the [2.0.0 SQL upgrades](https://github.com/coral-erm/coral/blob/master/resources/install/protected/2.0.0/001-000.sql). So upgrades from 1.x won't get the new columns, but fresh installs will.

We could patch this in a 3.0.1 patch that checks if the column exists and adds it if not, but we probably should provide a manual patch for people running 2.0.0 still.

**Comment by bmenk** [comment]
You're right - I overlooked that table using phpMyadmin, but saw that it was there from the command line. I was missing these three columns: priceTaxExcluded, taxRate, pricetaxIncluded.  Given this upgrade to date has just been to a test instance and that I'll have to re-do it all for our production instance, I for one would surely appreciate a 3.0.1 patch that checks for missing columns. It would make for a smoother upgrade process and leave one felling more confident overall about the integrity of the datatables after the upgrade is done. Thanks for your help. Bobb

**Comment by keelyward** [comment]
I can confirm this is also happening on our system. Thank you!

**Comment by jeffnm** [comment]
A fix has been merged and will be included in the next release.
