### ISSUE TITLE
Cannot delete Acquisition Type in Resources Admin

### ISSUE THREAD

**Issue by LibClaire** [coral-erm/coral#479]
We can add and edit Acquisition Types in the Resources Admin area but cannot delete them. The pop up confirming the delete appears but nothing happens when ok is clicked

[Tue Sep 04 14:39:33.696900 2018] [:error] [pid 9535] [client 10.250.4.201:53913
] PHP Fatal error:  Uncaught exception 'Exception' with message 'Es gab ein Prob
lem mit der Datenbank: Unknown column 'acquisitionTypeID' in 'where clause'' in
/var/www/html/coral3/resources/admin/classes/common/DBService.php:52\nStack trac
e:\n#0 /var/www/html/coral3/resources/admin/classes/common/DBService.php(91): DB
Service->checkForError()\n#1 /var/www/html/coral3/resources/admin/classes/domain
/AcquisitionType.php(61): DBService->processQuery('SELECT count(*)...', 'assoc')
\n#2 /var/www/html/coral3/resources/ajax_processing/deleteInstance.php(8): Acqui
sitionType->getNumberOfChildren()\n#3 /var/www/html/coral3/resources/ajax_proces
sing.php(26): include('/var/www/html/c...')\n#4 {main}\n  thrown in /var/www/htm
l/coral3/resources/admin/classes/common/DBService.php on line 52, referer: https
://coral.bsz-bw.de/coral3/resources/admin.php

**Comment by LibClaire** [comment]
This seems to be the case for Storage Types too.

**Comment by jeffnm** [comment]
A fix has been merged and will be included in the next release.
