### ISSUE TITLE
COUNTER Release 3 for SUSHI

### ISSUE THREAD

**Issue by vinny75** [coral-erm/coral#480]
Is COUNTER Release 3 still valid? http://www.niso.org/schemas/sushi/counter_sushi3_0.wsdl throws a 404, and SUSHI v3 is not even listed on https://www.niso.org/schemas/sushi.

**Comment by techsvcslib** [comment]
No, it’s not, but some vendors still provide reports in this version, believe it or not. Also the Usage Statistics module (and Usage Reporting sub-module) need to be updated to fully support release 4 and the newer version 5. This is a big project.

Steve

**Comment by vinny75** [comment]
I think the problem is, even if they provide reports in that format, SUSHI will not work for that format because it errors out since the WSDL can't be found.
