### ISSUE TITLE
Licensing: Helpful Links sidebar not fetching Resource links

### ISSUE THREAD

**Issue by jsavell** [coral-erm/coral#486]
A query in the getResourceArray method in the Licensing class needs to be refactored to join through the ResourceAcquisition table.

**Comment by jzairo** [comment]
we have experienced the same issue with the Helpful Links sidebar empty.

**Comment by sbouis** [comment]
We have experienced this issue too.

**Comment by veggiematts** [comment]
Fixed on the development branch. Fix will be part of the next release.
