### ISSUE TITLE
No duplicate warning when manually importing resources

### ISSUE THREAD

**Issue by LibClaire** [coral-erm/coral#490]
When doing a file import of resources using a .csv file there is no warning if a title already exists in CORAL and creates a duplicate. When adding a resource through the form manually, you are warned that the title already exists. It would be nice if this was the same for the file import.

**Comment by veggiematts** [comment]
Did you use ISBN/ISSN deduping in the import configuration ? 
You can check "Dedupe on this column" to prevent duplicates from being created.

**Comment by LibClaire** [comment]
I did not, thank you! :)
