### ISSUE TITLE
Notes not added with Import Tool

### ISSUE THREAD

**Issue by poacherone** [coral-erm/coral#491]
Using Coral 3.0.0 and the Import Tool, resource notes (ResourceNote) aren't handled correctly. The notes are imported by the entityID is set to NULL. Looking at the code it looks like the value is passed using the old ID name (resourceID) at line 691 in [import.php](https://github.com/coral-erm/coral/blob/master/resources/import.php).

**Comment by veggiematts** [comment]
Fixed by #471
