### ISSUE TITLE
Date issue with SUSHI Service Imports

### ISSUE THREAD

**Issue by LibClaire** [coral-erm/coral#494]
Using the SUSHI service: 
We are able to make a connection to the publisher and the data appears in the outstanding import queue. After clicking on view to process, the data is all displayed in the Import Confirmation, but instead of JR1 for January 2018 - September 2018 (the selected dates) the heading of the page is "Journals (JR1) R4 for January 2018 - February 2018". After clicking on confirm only the January and February data is imported even though there is data for March - Sept too.
A second attempt to load the data then offers the missing dates in the optional parameters window. Submitting this displays the data for March - September on the import confirmation page but the heading is once again for January 2018 - February 2018. On import nothing happens as the data for January and February is already there.
The date range January - February seems to be saved somehow as trying to change the dates for imports has no effect.

**Comment by vinny75** [comment]
See #484

**Comment by LibClaire** [comment]
Thanks, I can confirm it was the same issue and the fix you posted worked for us.
