### ISSUE TITLE
Invalid default date value

### ISSUE THREAD

**Issue by jamesrf** [Coral-erm/Coral#50]
When trying to install the latest version of Coral resources, I get this error:

> Invalid default value for 'updateDate'
> 
> For statement: CREATE TABLE `ResourceNote` ( `resourceNoteID` int(11) NOT NULL auto_increment, `resourceID` int(11) default NULL, `noteTypeID` int(11) default NULL, `tabName` varchar(45) default NULL, `updateDate` timestamp NOT NULL default '0000-00-00 00:00:00', `updateLoginID` varchar(45) default NULL, `noteText` text, PRIMARY KEY (`resourceNoteID`) ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8`

I am using PHP 5.6 and MySQL 5.7

For newer verisons of MySQL, strict mode has been changed and you cannot use '0000-00-00' as a default date without changing some settings in MySQL.

My suggestion instead would be to instead set the default value to be "NOW()", or to enable NULL values.

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes
http://stackoverflow.com/questions/25349126/how-can-i-set-the-default-value-of-a-field-as-0000-00-00-000000

Happy to make a PR for this if it sounds like a reasonable solution, however I'm not entirely sure yet how that field is used or what makes most sense for existing installs, or how this would be handled in an upgrade.

**Comment by tuxayo** [comment]
Confirmed, this prevents installing Coral with the version of MySQL(5.7) shipping with Ubuntu 16.04

**Comment by remocrevo** [comment]
@jamesrf Yes, please make a PR. I think your suggestion is a good solution.

**Comment by tuxayo** [comment]
I'm blocked by this so I'll use `updateDate timestamp DEFAULT CURRENT_TIMESTAMP` and make a PR if the install works with that.

In addition to the default values, `0000-00-00` is used in many other places https://framagit.org/snippets/283

That shouldn't impact the other usages of `0000-00-00` right?
