### ISSUE TITLE
Unable to create any document in management

### ISSUE THREAD

**Issue by Paulneverstop** [coral-erm/coral#502]
There are no options in categories. How can I solve it?
![management](https://user-images.githubusercontent.com/44267998/47164443-a4192a80-d32a-11e8-92a9-23ce84465da2.jpg)
![management1](https://user-images.githubusercontent.com/44267998/47164333-7207c880-d32a-11e8-8e84-749fa7ac522e.jpg)

**Comment by veggiematts** [comment]
Any error message in the log files?

**Comment by Paulneverstop** [comment]
> Any error message in the log files?

No.

**Comment by streatim** [comment]
Resolved with PR #703.

**Comment by Paulneverstop** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
