### ISSUE TITLE
Misleading error message when importing usage statistics

### ISSUE THREAD

**Issue by LibClaire** [coral-erm/coral#508]
When trying to upload a file in Usage Statistics this error message can appear:

![grafik](https://user-images.githubusercontent.com/25118486/47490102-4a43c380-d848-11e8-962e-1d2e15de357f.png)

This can be misleading as in this case it was not to do with file which was 42kb, but with the permissions in the usage directory. (Granting permissions fixes the import fail) It might be more helpful to display a different error message.

These were the warnings in the logs:

PHP Warning:  move_uploaded_file(/var/www/html/coral/coral-3.0.0/coral-3.0.0/usage
/archive/20181025.CORAL_JR1_EBSCO_TEST.txt): failed to open stream: Permission denied in /var/www/html/coral/coral-3.0.0/coral-3.0.0/usage/uploadConfirmation.php
on line 114, referer: http://localhost/coral/coral-3.0.0/coral-3.0.0/usage/import.php

PHP Warning:  file_get_contents(/var/www/html/coral/coral-3.0.0/coral-3.0.0/usage/
archive/20181025.CORAL_JR1_EBSCO_TEST.txt): failed to open stream: No such file or directory in /var/www/html/coral/coral-3.0.0/coral-3.0.0/usage/admin/classes/co
mmon/Utility.php on line 125, referer: http://localhost/coral/coral-3.0.0/coral-3.0.0/usage/import.php

**Comment by veggiematts** [comment]
Fixed by PR #562 and #580
