### ISSUE TITLE
SUSHI harvesting not working for multiple vendors

### ISSUE THREAD

**Issue by cjc66** [coral-erm/coral#513]
The following behavior is present with Oxford University Press, Credo, Gale, and Accessible Archives (possibly more)  in CORAL 3.0. The test connection is successful, but when they run the report it brings them to the following blank screen. If the user backs out and looks at SUSHI history, there is no indication the connection was run and there are no results.

![image](https://user-images.githubusercontent.com/17346824/48515552-40e1c180-e81e-11e8-9fd9-7286abfbe37b.png)

**Comment by vinny75** [comment]
Check /var/log/httpd/error_log for any errors that can help narrow the problem down.

**Comment by andyp-uk** [comment]
I believe this issue was addressed some time ago by #611
