### ISSUE TITLE
Datepicker not providing correct date format

### ISSUE THREAD

**Issue by poacherone** [Coral-erm/Coral#520]
When formating how dates are displayed (either changing common/common_directory.php or applying [PR 518](https://github.com/coral-erm/coral/pull/518)) the datepicker still uses the default format when choosing a date from the calendar. It saves ok, but it looks odd that the chosen date format ins't respected by the datepicker/calendar. This behavior is the same wherever the datepicker is used: orders, cost history, searching resources for date created, the effective date for a document in the License module etc.

**Comment by veggiematts** [comment]
Before a patch is made, you can fix the datepicker's behavior by changing the `Date.format` value in each module's `js/common.js`:

```
//suggested: mm/dd/yyyy OR dd-mm-yyyy
Date.format = 'dd/mm/yyyy';

```
