### ISSUE TITLE
Number of attachments in resources module

### ISSUE THREAD

**Issue by sbouis** [coral-erm/coral#526]
Before the 3.0 version of Coral, we could see the number of attachements next to "attachements" in the tab wording when we click on a resource. It still exists in the Licensing module.
Could you have it back in the resources module ?
![image](https://user-images.githubusercontent.com/31436815/51040672-668a0d80-15b8-11e9-90c5-2a7772221a62.png)
![image](https://user-images.githubusercontent.com/31436815/51040718-815c8200-15b8-11e9-9486-bb0efb5a8921.png)

**Comment by veggiematts** [comment]
Broken on master, fixed on the development branch.

**Comment by veggiematts** [comment]
(fixed by https://github.com/coral-erm/coral/commit/ee8848754e95c3d0d2700f0b4daf2e66d1afea8f )
