### ISSUE TITLE
developers call, join us 

### ISSUE THREAD

**Issue by t4k** [coral-erm/coral#531]
## Current Dev Call Information
Next Meeting: April 29 at 10AM CDT (8AM Pacific)
Location: https://meet.jit.si/CORALdevs

___
## Original Issue content:

https://doodle.com/poll/m8vems7reapkc2my

We will be meeting online, likely with Jitsi Meet, in the next week or two. Please fill out the poll if you are interested in the time being convenient for you.

**Comment by t4k** [comment]
We’ll meet at 8am Pacific Time on February 12 , and at 8am Pacific Time on February 21.

To join the video meeting, click this link: https://meet.jit.si/CORALdevs
To join by phone, dial +1.512.402.2718 and enter this PIN: 2189822786#
To view more phone numbers, click this link: https://meet.jit.si/static/dialInInfo.html?room=CORALdevs

**Comment by jeffnm** [comment]
Is it ok if we just edit the original post with the currently scheduled meeting and access? I think we can keep using the same Jitsi meet room indefinitely. I've pinned this issue so anyone interested in contributing will hopefully feel free to join us. 

I'm proposing that we try February 28 at 8am Pacific Time for our next call.

**Comment by t4k** [comment]
I'm in the room, but no one else is today. I'll stick around for a few more minutes then I have to go through airport security.

**Comment by jeffnm** [comment]
I'm horribly behind on CORAL work, but I think we should have a developers call in the next week or two before the May Steering Committee meeting if possible. 

Here's a Doodle Poll for some times that I think might work: https://doodle.com/poll/562bwd9xa7zaty6h

**Comment by jeffnm** [comment]
It looks like Monday April 29th at 10 AM CDT (8 AM Pacific) works best for those who have responded, so we'll plan on that. We can use the same Jitsi meeting as the previous times. https://meet.jit.si/CORALdevs

Anyone who is interested in development for CORAL is welcome to join.

**Comment by t4k** [comment]
I missed this update to this issue. I'm sorry.

**Comment by jeffnm** [comment]
No problem. We reviewed some pull requests. I also edited the [wiki page](https://github.com/coral-erm/coral/wiki/DT-Meetings) and edited the [first comment](https://github.com/coral-erm/coral/issues/531#issue-407802455) of this issue with the current call information, which we can update when we schedule the next call.
