### ISSUE TITLE
php 7 compatibility 

### ISSUE THREAD

**Issue by tuxayo** [Coral-erm/Coral#54]
When setting up the project with PHP 7
And running going to /management/install/
I see in the logs `Call to undefined function mysql_connect() in /srv/http/coral/management/install/CORALInstaller.php:35`
Which is a function of the mysql PHP extension
Which has been removed in PHP 7, as summed up [here](https://github.com/Coral-erm/Coral/pull/1#issuecomment-217863216)

There was already [work done in the admin and install modules](https://github.com/ndlibersa/resources/commit/26ae17cbbc7a9b0d65786d7bd40dc6f61605c015).

Grepping in the code shows that the Management and Report module are the last places using `mysql_connect()` and `mysql_query()`

I'll try to migrate them using the existing work.

**Comment by jeffnm** [comment]
CORAL doesn't officially support PHP 7, but the mysql vs. mysqli is an issue. 

It appears that the management module never had its mysql functions converted to mysqli. This includes the installer, but also DBService.php.  If you are going to attempt to update it, would you be willing to do the whole module?

**Comment by tuxayo** [comment]
> If you are going to attempt to update it, would you be willing to do the whole module?

That's what I planned to do if I manage to understand well enough the conversion process.

**Comment by tuxayo** [comment]
Just for anyone wondering, as #75 has been merged in the master branch, (code candidate for the next release) there is initial PHP 7 support.
As of now there aren't any known issues. But very few QA/testing has been done so issues might have yet to be discovered so anyone is welcome to do QA/testing or development using PHP 7 instead of PHP 5.

**Comment by jeffnm** [comment]
I think CORAL supports PHP 7 now. If future issues are identified that cause issues with that particular version of PHP, we'll open new issues to deal with them.  We officially support PHP 5.5 and higher with 2.0.0
