### ISSUE TITLE
ILS Connection: Vendor name not retrieved from Koha

### ISSUE THREAD

**Issue by LibClaire** [coral-erm/coral#550]
The full vendor name is not pulled through from Koha when retrieving vendor information from the ILS.

For Example, if I have a vendor in Koha called 'Book Supplier' and add a new vendor in CORAL I can type 'Boo' and check if it already exists in Koha. If I then retrieve the information it pulls through the relevant fields except the name and then greys it out leaving me with 'Boo' as the vendor name instead of Book Supplier.

It would be good if the full name was also pulled through to CORAL.

**Comment by veggiematts** [comment]
Obsoleted by #551
