### ISSUE TITLE
licensing and usage install: error in mysqli connection error handling

### ISSUE THREAD

**Issue by tuxayo** [Coral-erm/Coral#58]
During the install I got multiple times these messages:
- PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in [/srv/http/coral/licensing/install/CORALInstaller.php on line 57](https://github.com/Coral-erm/Coral/blob/master/licensing/install/CORALInstaller.php#L57), referer: http://localhost/coral/licensing/install/install.php
- PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in [/srv/http/coral/usage/install/CORALInstaller.php on line 69](https://github.com/Coral-erm/Coral/blob/master/usage/install/CORALInstaller.php#L69), referer: http://localhost/coral/usage/install/install.php

The problem was in the mysql → mysqli conversion, because replacing `mysql_connect` by `mysqli_connect` is not enough. Here is an example of a correct one:
https://github.com/ndlibersa/resources/commit/26ae17cbbc7a9b0d65786d7bd40dc6f61605c015#diff-2eb558a4ae0bd19dc896cd22fadbfa52L85
- [ ] TODO: search for other wrong mysqli instantiations.

**Comment by jeffnm** [comment]
This is no longer an issue with the new 2.0.0 unified installer.
