### ISSUE TITLE
CORALInstaller tries to connect with NULL db credentials

### ISSUE THREAD

**Issue by tuxayo** [Coral-erm/Coral#59]
During the install I got multiple times these messages:
- PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in [/srv/http/coral/licensing/install/CORALInstaller.php on line 57](https://github.com/Coral-erm/Coral/blob/master/licensing/install/CORALInstaller.php#L57), referer: http://localhost/coral/licensing/install/install.php
- PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in [/srv/http/coral/usage/install/CORALInstaller.php on line 69](https://github.com/Coral-erm/Coral/blob/master/usage/install/CORALInstaller.php#L69), referer: http://localhost/coral/usage/install/install.php

Other than #58, it shows that when [CORALInstaller is instantiated](https://github.com/Coral-erm/Coral/blob/master/licensing/install/install.php#L3), it [calls connect](https://github.com/Coral-erm/Coral/blob/master/licensing/install/CORALInstaller.php#L41) without any arguments, which leads to a connection failure but it **doesn't seem** to affect the install.

In that case, the credentials should [come from the config file](https://github.com/Coral-erm/Coral/blob/master/licensing/install/CORALInstaller.php#L49) but on a fresh install, it's empty.

It's suspicious, because it should be handled instead of trying to connect and causing a "false failure" right?

On other modules I remember seeing somewhere a message about trying to log to mysql with NULL credentials and thought it was a security check. But it was actually this issue without #58 interfering.

**Comment by tuxayo** [comment]
Also this causes a message at setup
![capture d ecran_2016-07-04_11-47-06](https://cloud.githubusercontent.com/assets/2678215/16556960/4c179fe6-41dd-11e6-8a03-d7f330eae7c8.png)

**Comment by remocrevo** [comment]
@jeffnm Does this problem need to be addressed, or does the new installer remove this problem?

**Comment by jeffnm** [comment]
@remocrevo let me double check, but the new installer should resolve this issue.

**Comment by jeffnm** [comment]
@jcuenod Can you confirm that the new installer resolves this? I've not seen it happen in my testing of the new installer.

**Comment by jcuenod** [comment]
Sure, I'll get onto this tomorrow afternoon.

**Comment by jcuenod** [comment]
There might be an edge case that I haven't found but I'm pretty confident that this won't happen with the new installer.
