### ISSUE TITLE
Behaviour of browser back-button and Coral

### ISSUE THREAD

**Issue by poacherone** [coral-erm/coral#601]
In the resource module, if you do a search for a resource (or browse to another pagination, use one of the filtering options etc.), click through to a resource, and then use the browsers back-button the behaviour is today that the values from the search/browsing/filtering is gone and all resources display. The expected behaviour from staff here would be for their searches (etc.) to be kept.

Various browsers handles this differently though. Chrome for example will keep a search or filtering, but not pagination, while Firefox retains none of the options.

If it is not possible to provide the same behaviour in all browsers, then perhaps a link back to the search results can be displayed on the resource somewhere (a common option used in other systems).

**Comment by ehartnett** [comment]
I'd be in favor of this functionality being added. The Licensing module retains your search when you go into a record and then back out. Could the same code be used in Resources?

**Comment by veggiematts** [comment]
Actually this feature seems to exist already for the resource module but is somehow broken. I'll try to come up with a fix.
