### ISSUE TITLE
Automatic e-mail is not working.

### ISSUE THREAD

**Issue by subratlubu** [coral-erm/coral#617]
When I was entering the details in report new issue tab in resource module and click on the submit button, the automatic mail was not sent to the assigned person. Kindly look into the matter.
![69272089-0d3d3280-0bfc-11ea-9f6f-17584334f576](https://user-images.githubusercontent.com/58173344/69539392-61ecfe80-0faa-11ea-936d-dc4922d0d161.png)

**Comment by veggiematts** [comment]
Duplicate of #615
