### ISSUE TITLE
Dashboards are not displaying correctly grouped information anymore

### ISSUE THREAD

**Issue by sbouis** [coral-erm/coral#633]
On the development branch, dashboards (statistics and yearly costs) are not sorting correctly the information when you choose to group by something else than resources. Everything is grouped alphabetically, so the sub-totals and total lines are not displayed where they should be.
You can see it on the video attached.
[2020-02-21_14-36-27.zip](https://github.com/coral-erm/coral/files/4236499/2020-02-21_14-36-27.zip)

**Comment by veggiematts** [comment]
Fixed by PR #634
