### ISSUE TITLE
Management: install doesn't allow to configure Organizations interoperability

### ISSUE THREAD

**Issue by tuxayo** [Coral-erm/Coral#67]
In the "new document" form, this prevents the `Categories` select to show the created consortiums.

Manually editing `management/admin/configuration.ini`  allows to use the consortiums.

note: `management/admin/configuration.ini` contains also Usage and Resources settings and the install also doesn't expose them.

**Comment by jeffnm** [comment]
@jcuenod can you comment if this is relevant to the 2.0.0 installer?

**Comment by jcuenod** [comment]
Were these in the previous installer?
The config file that the current installer generates includes lines like

    managementModule = "Y"
    managementDatabaseName = "coral_management"

This may as well be part of the form though but I don't know what options need to be exposed...

**Comment by jeffnm** [comment]
My understanding is that they existed in the `configuration_sample.ini` for Management, but the installer didn't know whether or not those other modules were installed and there was no way for the user to tell it they were.  

Based on my understanding of our new installer and the way the old installer worked, I don't believe this should be a problem as you are automatically setting module and database info during the install. 

The fact that management module's config file is populated with:
```
organizationsModule=N
organizationsDatabaseName=
```
means I'm pretty confident that this is no longer an issue. I just wanted to confirm with you.
