### ISSUE TITLE
Coral Installer Failed

### ISSUE THREAD

**Issue by jmelvin71** [coral-erm/coral#675]
Trying to install Coral for the first time. Downloaded the latest version 2020.09 and running the installer. Receiving the following error from the browser: 

Fatal error:  Array and string offset access syntax with curly braces is no longer supported in coral\auth\install\auth.php on line 16

I am installing on a virtual Windows Server 2016 running Apache 2.4, PHP 8.0, and MySQL 8.0. I know that PHP version 7.4 deprecated the curly brace for accessing array elements and string offsets, but I am not seeing any in the auth.php file (unless I missed it). Is there something I missed in setup or that needs to be done differently with the latest version or will PHP 8.0 not work with Coral. The installation instructions I am following is for a previous version. I do not see any updated instructions for the latest version. Any help appreciated.

**Comment by quornicus** [comment]
I refreshed a Coral installation in June and it couldn't deal with any version of PHP over 7.0. Perhaps that's no longer an issue, but it may be worth a shot if you're still having problems.

**Comment by streatim** [comment]
Looking over the file in question it appears that the curly braces have been switched over to brackets as part of the PHP 8 Compatibility update that was pushed out earlier this year in 2024.04.
