### ISSUE TITLE
Nothing happens when clicking the button to add parents in a product detail

### ISSUE THREAD

**Issue by sbouis** [coral-erm/coral#679]
It occurs in our 2020.09 version. I tried in the demo website and it is the same.
To reproduce :
- Click on a title in the resource module
- Go to the Product tab and edit the product
- Try to click on the "add" button in the parents field
- > Nothing happens

![image](https://user-images.githubusercontent.com/31436815/110796910-c784fd00-8278-11eb-8088-a1a54c5b3091.png)

**Comment by veggiematts** [comment]
Did you try typing something in the input field and wait for the completion ?

**Comment by sbouis** [comment]
No, I didn't. But now, I tried ;-)
It's the same...
I keep clicking on "add" and nothing changes. If I click on "submit", no parent resource is saved. 
![image](https://user-images.githubusercontent.com/31436815/110800190-3e6fc500-827c-11eb-8d92-fa349d900b9d.png)

**Comment by veggiematts** [comment]
Seems broken on master, too. Javascript error:

 Syntax error, unrecognized expression:  .oneParent [name='parentResourceNewID']'

**Comment by kfischer** [comment]
We see the same problem in 2020.09. Is there any workaround or fix we could apply?

**Comment by xsong9** [comment]
I can replicate the issue on our local 2020.09 instance. I can bring it up at the next SC meeting. Meanwhile, if anyone has any workaround or suggestions, please share them here.

**Comment by andyp-uk** [comment]
This is fixed by PR #680
