### ISSUE TITLE
Unable to get past MYSQL installation error "Sorry, an error we have not accounted for has occurred ."

### ISSUE THREAD

**Issue by gar71** [coral-erm/coral#685]
Running on FreeBSD 11, MYSQL 8, PHP 7.4, Apache 2.4.  Verified that my root mysql passwords works on the server and all GRANTS are granted.  

CORAL Installed Failed 

Sorry, an error we have not accounted for has occurred .

NULL
We haven't prepared for the following error (have_database_access.php #1):

object(RuntimeException)#43 (7) {
  ["message":protected]=>
  string(39) "There was a problem with the database: "
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(55) "/usr/local/www/apache24/data/coral/common/DBService.php"
  ["line":protected]=>
  int(59)
  ["trace":"Exception":private]=>
  array(11) {
    [0]=>
    array(5) {
      ["file"]=>
      string(74) "/usr/local/www/apache24/data/coral/install/providers/get_db_connection.php"
      ["line"]=>
      int(38)
      ["function"]=>
      string(11) "__construct"
      ["class"]=>
      string(9) "DBService"
      ["type"]=>
      string(2) "->"
    }
    [1]=>
    array(3) {
      ["file"]=>
      string(77) "/usr/local/www/apache24/data/coral/install/providers/have_database_access.php"
      ["line"]=>
      int(169)
      ["function"]=>
      string(9) "{closure}"
    }
    [2]=>
    array(3) {
      ["file"]=>
      string(56) "/usr/local/www/apache24/data/coral/install/installer.php"
      ["line"]=>
      int(281)
      ["function"]=>
      string(9) "{closure}"
    }
    [3]=>
    array(5) {
      ["file"]=>
      string(56) "/usr/local/www/apache24/data/coral/install/installer.php"
      ["line"]=>
      int(272)
      ["function"]=>
      string(15) "actuallyRunTest"
      ["class"]=>
      string(9) "Installer"
      ["type"]=>
      string(2) "->"
    }
    [4]=>
    array(5) {
      ["file"]=>
      string(56) "/usr/local/www/apache24/data/coral/install/installer.php"
      ["line"]=>
      int(265)
      ["function"]=>
      string(16) "runTestForResult"
      ["class"]=>
      string(9) "Installer"
      ["type"]=>
      string(2) "->"
    }
    [5]=>
    array(5) {
      ["file"]=>
      string(56) "/usr/local/www/apache24/data/coral/install/installer.php"
      ["line"]=>
      int(265)
      ["function"]=>
      string(16) "runTestForResult"
      ["class"]=>
      string(9) "Installer"
      ["type"]=>
      string(2) "->"
    }
    [6]=>
    array(5) {
      ["file"]=>
      string(56) "/usr/local/www/apache24/data/coral/install/installer.php"
      ["line"]=>
      int(265)
      ["function"]=>
      string(16) "runTestForResult"
      ["class"]=>
      string(9) "Installer"
      ["type"]=>
      string(2) "->"
    }
    [7]=>
    array(5) {
      ["file"]=>
      string(56) "/usr/local/www/apache24/data/coral/install/installer.php"
      ["line"]=>
      int(265)
      ["function"]=>
      string(16) "runTestForResult"
      ["class"]=>
      string(9) "Installer"
      ["type"]=>
      string(2) "->"
    }
    [8]=>
    array(5) {
      ["file"]=>
      string(52) "/usr/local/www/apache24/data/coral/install/index.php"
      ["line"]=>
      int(112)
      ["function"]=>
      string(16) "runTestForResult"
      ["class"]=>
      string(9) "Installer"
      ["type"]=>
      string(2) "->"
    }
    [9]=>
    array(3) {
      ["file"]=>
      string(52) "/usr/local/www/apache24/data/coral/install/index.php"
      ["line"]=>
      int(196)
      ["function"]=>
      string(8) "run_loop"
    }
    [10]=>
    array(4) {
      ["file"]=>
      string(44) "/usr/local/www/apache24/data/coral/index.php"
      ["line"]=>
      int(4)
      ["args"]=>
      array(1) {
        [0]=>
        string(52) "/usr/local/www/apache24/data/coral/install/index.php"
      }
      ["function"]=>
      string(12) "require_once"
    }
  }
  ["previous":"Exception":private]=>
  NULL
}

**Comment by LuckyGuyMike** [comment]
I responded to this elsewhere, so this is just a copy/paste from the other post:

This problem is caused by the way MySQL handles the authentication ("auth_socket") vs "mysql_native_password".
The fix: Switch the authentication method, continue with the install, and then change it back when installation finishes.

-Here's a reference link that has the steps you'll need to use: https://devanswe.rs/how-to-fix-failed-error-set-password-has-no-significance-for-user-rootlocalhost/
