### ISSUE TITLE
Compatibility with PHP 8.x

### ISSUE THREAD

**Issue by ajones3066** [coral-erm/coral#688]
The requirements for PHP 7.x will be reaching end of life soon. Is there any plan to upgrade the code to PHP 8.x and MySQL 10?

Thanks

**Comment by andyp-uk** [comment]
Yes, the work to support PHP v8.1.1 has been done to https://github.com/sirsidynix/coral and will be merged into coral-erm/coral later this year. Changes were made under https://github.com/Sirsidynix/coral/pull/30.

**Comment by ajones3066** [comment]
@andyp-uk - which rdbms should we use mysql8? mariadb?  thanks.

Allen

**Comment by andyp-uk** [comment]
We are using MariaDB 5.5.68 for the time being.

**Comment by andyp-uk** [comment]
As a footnote, we are now using Mariadb 10.11.7 without problem. This did not require any code changes.
