### ISSUE TITLE
Date Picker Populates double days

### ISSUE THREAD

**Issue by jzairo** [coral-erm/coral#689]
The date picker in Organizations, Resources, Licensing is populating double days for November 7, 2021. This causes the rest of the calendar year to be off by a day. 
![Screen Shot 2021-09-10 at 11 35 40 AM](https://user-images.githubusercontent.com/33321773/132879679-4e25c97e-5845-4133-a023-2db2e69b7072.png)

**Comment by andyp-uk** [comment]
I'm not able to replicate this.

**Comment by quornicus** [comment]
A user unintentionally replicated this today. Same week, same month, different year.
![coral-date-picker](https://github.com/coral-erm/coral/assets/5781404/f7b1ac59-919d-4aaa-a507-767793d2e524)

**Comment by streatim** [comment]
At present unable to replicate, though I believe that's because this appears to be the issue resolved in PR #749.  We can tentatively close the issue unless it continues to be replicated by users.
