### ISSUE TITLE
resources: New Resource: handle the case where there is no resource type

### ISSUE THREAD

**Issue by tuxayo** [coral-erm/coral#69]
When opening the form:
![capture d ecran_2016-07-06_11-26-35](https://cloud.githubusercontent.com/assets/2678215/16613474/92dd1ef2-436c-11e6-81c5-fdb9d837ebfb.png)
When validating:
![capture d ecran_2016-07-06_11-26-53](https://cloud.githubusercontent.com/assets/2678215/16613473/92d8d1ee-436c-11e6-90ef-c114813f2437.png)

**Comment by xsong9** [comment]
I ran a test record and saw the Resource Type was not required to have record submitted. See the screen capture below:
https://www.screencast.com/t/nZossTZJ

**Comment by xsong9** [comment]
Format and Acquisition Type are required when creating a new record. It's ok to not require a Resource Type.
