### ISSUE TITLE
Queries testing for empty strings in Date fields throws fatal error under MySQL version 8.x

### ISSUE THREAD

**Issue by KerryBouchard** [coral-erm/coral#698]
We are on CORAL 3.0.0. We moved our database to MySQL version 8.0 in December, and recently noticed that the "Contacts" links in the Organizations module had stopped working. After turning on display_errors for our php-fpm server, that turned out to be caused by two queries in the /opt/projects/coral/organizations/admin/classes/domain/Organization.php file:

`$query = "SELECT * FROM Contact WHERE (archiveDate = '0000-00-00' || archiveDate = '' || archiveDate is null) AND organizationID = '" . $this->organizationID . "' order by name";
`
and:

`$query = "SELECT * FROM Contact WHERE (archiveDate != '0000-00-00' && archiveDate != '') AND organizationID = '" . $this->organizationID . "' order by name";
`

Testing for an empty string for a Date field throws a fatal error in MySQL v8.x, and turning off "strict mode" on the MySQL server did not fix that, so we removed the "archiveDate = '' " and archiveDate != '' " tests from the code.

Is removing empty string tests for Date fields a change anticipated for new CORAL releases so that compatibility with newer MySQL releases will be maintained?

Thanks, Kerry Bouchard

**Comment by streatim** [comment]
A fix for this was pushed as part of the 2024.04 Release - linking the specific commit below:
[Move Organization module to modern mysql date style (null rather than 0000-00-00) but leave support for older mysql versions in place](https://github.com/coral-erm/coral/commit/e4b4c06baf445a54e06bb3c0a481b618e6ed7e60)
