### ISSUE TITLE
Add an API to Coral

### ISSUE THREAD

**Issue by veggiematts** [coral-erm/coral#7]
Coral is currently missing an API, in order to be able to gather informations or interact with coral from within third-part applications.

For a start, I would be working on proposing a new resource from an external form, but many other things could be achieved afterwards.

A REST API is what I consider to be the best, as it's simple and efficient.

REST API are rarely developped from scratch: libraries are often used, in order to focus on the API itself, and not the HTTP technical stuff behind it.

I've checked several PHP REST libraries, and Flight seems to be an ideal candidate, as it's simple, lightweight, and quick to use.
http://flightphp.com/

Before dealing with more complex authentication systems (like token), a simple IP-based authorization would be easy to implement and operate.

**Comment by jeffnm** [comment]
As an aside, while it's not an API, you can get a lot of resource data out via the Public Interface Generator found in the Add-ons repository https://github.com/ndlibersa/CORAL_Addons which can output xml. 

An actual API would be nice.
