### ISSUE TITLE
JQuery version is affected by multiple cross site scripting vulnerabilities

### ISSUE THREAD

**Issue by dongourley** [coral-erm/coral#700]
According to CISA and Nessus, our Coral 2020.09 install uses a version of JQuery prior to 3.5.0. It is, therefore, affected by multiple cross site scripting vulnerabilities. Can we upgrade the version JQuery used? Or, at least, turn off the version self-reporting by JQuery on the initial login page?

**Comment by spaceisntsyntax** [comment]
Hi Don, there is work ongoing to update the version of JQuery (and other JS libraries) used by CORAL.  Unfortunately, CORAL uses some deprecated JQuery methods directly, as well as several JS widgets that assume a very old version, so you can't simply drop in a new version as a replacement.  We hope to have all the modules updated in the next few months.

**Comment by streatim** [comment]
[v2024.04 of CORAL ](https://github.com/coral-erm/coral/releases/tag/v2024.04) was released earlier this year, upgrading the jQuery version in CORAL to 3.6.0.
