### ISSUE TITLE
How to take back up & restore of CORAL? Please help.

### ISSUE THREAD

**Issue by subratlubu** [coral-erm/coral#704]

**Comment by shivadcedtu** [comment]
Steps for DB backup:
Take complete database backup. or take databases related to coral. like coral_resources,coral_auth,coral_usage,coral_organisations etc. by using the command like
mysqldump -u root -p<password> coral_resources > coral_resources_bkp.sql ---for db coral_resources
similarly for coral_usage
mysqldump -u root -p<password> coral_usages > coral_resource_bkp.sql 

Steps for restoration:
restore individual databases into the new coral or upgraded coral using the 

root@.../home/...# MYSQL DB_NAME < BACKUP-FILE.sql
                           #coral_resources > coral_resource_bkp.sql
#coral_resources db should be already there in the upgrade or new coral before restoring

Thanks

**Comment by subratlubu** [comment]
Thank you for your support.
