### ISSUE TITLE
remove /usage/old/ directory

### ISSUE THREAD

**Issue by tuxayo** [Coral-erm/Coral#74]
@remocrevo https://github.com/Coral-erm/Coral/issues/56#issuecomment-229362109

>  I believe the /usage/old/ directory should be removed, and therefore doesn't need to be updated. Can anyone confirm?

**Comment by tuxayo** [comment]
+1 because that adds noise when searching through the code.

**Comment by jeffnm** [comment]
I'm not aware of any use for the /usage/old directory.
