### ISSUE TITLE
SUSHI Registry Link Invalid

### ISSUE THREAD

**Issue by JohnYorio** [coral-erm/coral#746]
When you click on the link to " Visit the SUSHI Server Registry for information about adding your provider." you're taken to a "Page not found" message. 

This has happened before and was fixed: https://github.com/coral-erm/coral/issues/375 but that issue is closed.

As noted in the last comment on the above, the correct link may now be https://registry.projectcounter.org/

**Comment by rtatterson** [comment]
Updated in version 2024.04
