### ISSUE TITLE
Undisclosed File Size Limitation for Resource Attachments

### ISSUE THREAD

**Issue by LibrarianMike** [coral-erm/coral#763]
I tried attaching a large PDF quote (1.7 MB) to one of our resources and received the following error from the web server:

The file upload failed for the following reason: 413 error / 413 Request Entity Too Large 413 Request Entity Too Large nginx/1.10.3

Is this a CORAL restriction or server configuration restriction. The documentation for resource attachments doesn't mention any size limitations.

Reducing the file size avoided the issue, but I figured it was worth reporting.

**Comment by andyp-uk** [comment]
I'm not seeing this issue on my system. Bearing in mind the error appears to be coming from nginx, I suspect the restriction is not specific to CORAL but relates to the webserver on which CORAL is running.
