### ISSUE TITLE
Unable to edit or add new notes in eRM

### ISSUE THREAD

**Issue by TPLKelli** [coral-erm/coral#770]
I'm trying to add a note to the Cataloguing section for a resource and the eRM will not let me edit previous notes or add a new one.  I can delete.   Instead of the image of the paper and pencil, the add icon has changed to a green plus sign.   The edit icon looks the same. 

I'm using Edge Version 126.0.2592.56 (Official build) (64-bit).  I don't know if it was updated recently or not. 

Please fix. 

Thank you.

**Comment by andyp-uk** [comment]
I'm not able to replicate this issue. What version of CORAL are you using?

**Comment by TPLKelli** [comment]
Thanks for testing.  It's CORAL version 2024.04. 

No problems with Chrome, just Edge.   I'll try my personal computer, just in case there is something going on with my work laptop.

**Comment by andyp-uk** [comment]
That's so strange. I'm not seeing the problem in Edge either. I am using the same versions of CORAL and Edge as you.

**Comment by TPLKelli** [comment]
Well, it's definitely my work computer.  CORAL works just fine on my personal computer.  Same version of Edge.  I suspect that the pop-ups to add notes are being blocked. 

Sorry to bother you.   Thanks for trying to help me.
