### ISSUE TITLE
auth: translation: error message "Invalid translation route!" not visible

### ISSUE THREAD

**Issue by tuxayo** [coral-erm/coral#83]
Steps to reproduce:
- go to /auth
- the language drop down should contain english and french
- `mv auth/locale auth/locale.bak`
- refresh the page
- the language drop down should only contain english
- and the HTML contains

```
    <div class='boxRight'>
        <p class="fontText">Change language:</p>
        <select name="lang" id="lang" class="dropDownLang">
            <br>Invalid translation route!<option value='en_US'>English</option>
         </select>
    </div>
```
- but it's not visible on the page

**Comment by tuxayo** [comment]
Also happens in `/auth/admin.php`

It should happen in all files containing "Invalid translation route"

**Comment by xsong9** [comment]
Translation is no longer supported, so close this for now.
