### ISSUE TITLE
Enhancements to the workflows

### ISSUE THREAD

**Issue by veggiematts** [coral-erm/coral#9]
Restart a completed workflow: Users should be allowed to restart a new workflow by selecting a workflow from a pre-defined workflow list or restart the current completed workflow. The current CORAL functionality does not allow users to restart any already completed workflow. 

Ability to archive previous workflows: Previously completed workflows contain valuable information, such as date when tasks are completed, and such information should be kept. Currently CORAL does not support such functionality. 

Ability to add a step in the workflow for a particular resource: The ability to add a step offers users greater flexibility to determine a customized workflow for a specific resource. CORAL provides a globalized add a step function in the Admin section, which applies to all resources associated with this workflow, not on individual resource level. 

Receive assignment email notification with some context about the assignment:  Users have complained that the workflow assignment emails sent from CORAL do not contain much useful information. It would be helpful to embed a concise message in the email about the assignment rather than just “a resource is added to your queue” as is currently displayed. 

Send email reminder to users who are assigned to a step: Task reminders are often seen in project management application or task management tools. This functionality will remind users to complete the steps by a due date. CORAL has alert function in place now, but only for subscription alerts.

**Comment by benheet** [comment]
for a point of discussion, what is everyone's preference on the specificity of issues? for example, this issue notes several pieces of altered functionality. should these be pulled out into separate issues for more focused discussion or is containing them together in a single issue better?

**Comment by xsong9** [comment]
NCSU is working with Matt refining the development on individual function described here. Separate issues will be added soon. Meanwhile we are happy to collect any comment or feedback you may have about these functions.

**Comment by xsong9** [comment]
Have SC reviewed this issue yet? There is a pull request #117 for this issue.

**Comment by jeffnm** [comment]
#117 was merged over a year ago, I'm assuming this can be closed.
