### ISSUE TITLE
resources: search option <select>s loose their style when clicking the new resource button

### ISSUE THREAD

**Issue by tuxayo** [coral-erm/coral#90]
When I'm on the resources list
Then the search option <select>s [look fine](https://cloud.githubusercontent.com/assets/2678215/17096611/8eaac1d4-525a-11e6-925a-75cc05ed73f6.png)
When I click on the new resource button
Then I see that the <select>s [lost their style](https://cloud.githubusercontent.com/assets/2678215/17096654/c593f31e-525a-11e6-8595-581af237d5fd.png)
And the [style lost is persistent](https://cloud.githubusercontent.com/assets/2678215/17096709/03d3e666-525b-11e6-95be-4613535cca2b.png) after closing the new resource form.

For some reason, the `idleField` class is added to the <select>s. Removing it with the browser dev tools allows to get back the style.

**Comment by jeffnm** [comment]
I'm not able to reproduce this. Perhaps it's been fixed?

**Comment by xsong9** [comment]
Not able to replicate the reported issue, so close it now.
