### ISSUE TITLE
Infinite loading when trying to create a resource when session expired (no login redirect)

### ISSUE THREAD

**Issue by tuxayo** [coral-erm/coral#91]
The Ajax request for the form gets redirected
![capture d ecran_2016-07-29_12-41-34](https://cloud.githubusercontent.com/assets/2678215/17246071/0dbb59b6-558a-11e6-82c6-1aa3169e5841.png)

And the page stays in loading state indefinitely.
![capture d ecran_2016-07-29_12-41-11](https://cloud.githubusercontent.com/assets/2678215/17246052/f32b4d5e-5589-11e6-9a9d-d649bb7cdacf.png)

It possibly happens to every Ajax call. (searches and forms)

**Comment by tuxayo** [comment]
Related: "Warning: this name already exists." (in the new resource form) is shown systematically when the session expired.

**Comment by xsong9** [comment]
Not able to replicate the reported issue, so close it now.
