### ISSUE TITLE
Licensing: The footer is inside the content wrapper instead of after

### ISSUE THREAD

**Issue by tuxayo** [Coral-erm/Coral#97]
Which should (has?) lead to css issues due to this inconsistency with other modules.

For example, Licensing wasn't affected by:
https://github.com/Coral-erm/Coral/pull/96#issuecomment-237309275

**Comment by jeffnm** [comment]
I think this is no longer an issue. A quick browser inspection of the 2.0.0 beta licensing index shows that the footer div is now a child of <body>
